\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Thomas Hastings," \italic "Juvenile Songs," "1841" }
poet = \smallText \markup { "Text: James Skinner," \italic "Daily Service Hymnal," "1863, alt." }
meter = \smallText "RETREAT LM"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 1
tags = "english christian 4part"
dateAdded = "2026-08-02"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Great God, the giver of all good"
hymnKey = \key c \major
hymnTime = \time 6/4
quarternoteTempo = 120
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  \partial 4 e'8( f'8) | g'2 g'4 g'4( f'4) e'4 | a'2 a'4 g'2 b'8( c''8) | d''2 d''4 d''4( c''4) b'4 | c''2 e''4 d''2 \bar "" \break
  \partial 4 d''4 | e''2 d''4 c''2 a'4 | g'2 e'4 d'2 e'8( f'8) | g'2 g'4 g'4( f'4) e'4 | a'2. b'2. | c''2.~ c''2
\bar "|."
}
alto = { \globalParts
  \partial 4 c'8( d'8) | e'2 e'4 e'4( d'4) c'4 | c'2 f'4 e'2 d'8( e'8) | f'2 f'4 f'4( e'4) d'4 | e'2 g'4 g'2 g'4 | g'2 f'4 e'2 f'4 | e'2 c'4 b2 c'8( d'8) | e'2 e'4 e'4( d'4) c'4 | c'2. f'2. | e'2.~ e'2
}
tenor = { \globalParts
  \partial 4 c'4 | c'2 c'4 g2 c'4 | c'2 c'4 c'2 g4 | g2 g4 g2 g4 | g2 c'4 b2 b4 | c'2 c'4 c'2 c'4 | c'2 g4 g2 c'4 | c'2 c'4 g2 c'4 | c'2. g2. | g2.~ g2
}
bass = { \globalParts
  \partial 4 c4 | c2 c4 c2 c4 | f2 f4 c2 g4 | g2 g4 g2 g4 | c2 c4 g2 g4 | c2 c4 c2 c4 | c2 e4 g2 c4 | c2 c4 c4( d4) e4 | f2. g2. | c2.~ c2
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l Great God, the giv -- er of all good,
ac -- cept our thanks and bless this food.
\l Grace, health, and strength to us af -- ford,
through Je -- sus Christ, our ris -- en Lord.
}

% Set up music-aligned verses. Change to the correct number
\include "../../lib/1verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-1verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
