\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
%% The music attribution is long enough to collide with the poet's on one
%% line each, so both are split, as have-thine-own-way does.
composer = \twoLineSmallText \markup { "Music: American folk melody, in Joseph Funk's" } \markup { \italic "Genuine Church Music," "1st ed., 1832" }
poet = \twoLineSmallText \markup { "Text: “K” in Rippon's" } \markup { \italic "Selection of Hymns," "1787" }
meter = \smallText "FOUNDATION (BELLEVUE) 11 11. 11 11"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 5
tags = "english christian 4part"
dateAdded = "2026-07-27"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "How firm a foundation"
hymnKey = \key a \major
hymnTime = \time 2/2
quarternoteTempo = 160
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  %% Each of the three upbeats e'-fs' is slurred on the page - the photo
  %% shows two arcs on the pickup, one over the soprano pair and one under
  %% the alto pair, and every verse sets a single syllable across the two
  %% notes. from-xml.py carried the slur into the alto only and left the
  %% soprano bare, which would have set two syllables here and shifted the
  %% rest of all five verses by one.
  %%
  %% Four systems, each starting on its pickup, as the page prints them.
  %% \break because the break falls mid-measure, before the upbeat.
  \partial 2 e'4( fs'4) | a'2 fs'4 a'4 | e'2 a'4 a'4 | cs''2 a'4 cs''4 | e'2 \break e'4( fs'4) | a'2 fs'4 a'4 | e'2 a'4 a'4 | cs''2 b'4 b'4 | a'2 \break cs''2 | e''2 cs''4 e''4 | a'2 a'4 a'4 | cs''2 a'4 cs''4 | e'2 \break e'4( fs'4) | a'2 fs'4 a'4 | e'2 a'4 a'4 | cs''2 b'4 b'4 | a'2
\bar "|."
}
alto = { \globalParts
  \partial 2 cs'4( d'4) | e'2 d'4 fs'4 | e'2 cs'4 cs'4 | e'2 cs'4 a4 | b2 \break cs'4( d'4) | e'2 d'4 fs'4 | e'2 cs'4 cs'4 | e'2 e'4 e'4 | cs'2 \break e'2 | a'2 e'4 e'4 | fs'2 fs'4 fs'4 | e'2 cs'4 a4 | b2 \break cs'4( d'4) | e'2 d'4 fs'4 | e'2 cs'4 cs'4 | e'2 e'4 e'4 | cs'2
}
tenor = { \globalParts
  \partial 2 a2 | cs'2 a4 a4 | a2 e4 e4 | a2 a4 a4 | gs2 \break a2 | cs'2 a4 a4 | a2 a4 a4 | a2 gs4 gs4 | a2 \break a2 | cs'2 a4 b4 | cs'2 d'4 a4 | a2 a4 a4 | gs2 \break a2 | cs'2 a4 a4 | a2 a4 a4 | a2 gs4 gs4 | a2
}
bass = { \globalParts
  \partial 2 a,2 | a,2 d4 d4 | cs2 a,4 a,4 | a,2 a,4 a,4 | e2 \break a,2 | a,2 d4 d4 | cs2 fs4 fs4 | e2 e4 e4 | a,2 \break a2 | a2 a4 gs4 | fs2 d4 d4 | a,2 a,4 a,4 | e2 \break a,2 | a,2 d4 d4 | cs2 fs4 fs4 | e2 e4 e4 | a,2
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

%% One \l line per system, so each line after the first starts on that
%% system's upbeat. The converter emitted verse A with a leading \l and
%% B-E without one, and wrote the page's curly quotes as a doubled
%% apostrophe (''Fear), which sets a literal '' before the word; the
%% verses that open a quotation use a real left double quote instead.
verseA = \lyricmode {
\l How firm a foun -- da -- tion, ye saints of the Lord,
\l is laid for your faith in his ex -- cel -- lent Word!
\l What more can he say than to you he hath said,
\l to you who for ref -- uge to Je -- sus have fled?
}
verseB = \lyricmode {
\l “Fear not, I am with thee; O be not dis -- mayed,
\l for I am thy God, and will still give thee aid.
\l I'll strength -- en thee, help thee, and cause thee to stand,
\l up -- held by my right -- eous, om -- ni -- po -- tent hand.
}
verseC = \lyricmode {
\l “When through the deep wa -- ters I call thee to go,
\l the riv -- ers of sor -- row shall not o -- ver -- flow,
\l for I will be with thee, thy trou -- bles to bless,
\l and sanc -- ti -- fy to thee thy deep -- est dis -- tress.
}
verseD = \lyricmode {
\l “When through fi -- ery tri -- als thy path -- way shall lie,
\l my grace, all -- suf -- fi -- cient, shall be thy sup -- ply.
\l The flame shall not hurt thee. I on -- ly de -- sign
\l thy dross to con -- sume, and thy gold to re -- fine.
}
verseE = \lyricmode {
\l “The soul that on Je -- sus still leans for re -- pose,
\l I will not, I will not de -- sert to its foes.
\l That soul, though all hell should en -- deav -- or to shake,
\l I'll nev -- er, no nev -- er, no nev -- er for -- sake!”
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/5verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-5verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
