\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
%% Both attributions name the same long book, and on one line each they
%% collide in the middle of the page and run off the right edge. Split
%% across two lines apiece, the way of-the-fathers-love-begotten and
%% come-come-emmanuel handle their long sources.
composer = \twoLineSmallText \markup { "Music: George C. Stebbins," } \markup { \italic "Northfield Hymnal with Alexander's Supplement," "1907" }
poet = \twoLineSmallText \markup { "Text: Adelaide A. Pollard," } \markup { \italic "Northfield Hymnal with Alexander's Supplement," "1907, alt." }
meter = \smallText "ADELAIDE 54. 54D"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 4
tags = "english christian 4part"
dateAdded = "2026-07-27"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Have thine own way"
hymnKey = \key ef \major
hymnTime = \time 9/4
quarternoteTempo = 160
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  \partial 2. g'4 f'4 g'4 | af'2. g'2. ef'4 d'4 ef'4 | f'2.~ f'2. f'4 e'4 f'4 | g'2. f'2. f'4 ef'4 d'4 | ef'2.~ ef'2. g'4 f'4 g'4 | af'2. g'2. bf'4 a'4 bf'4 | c''2.~ c''2. c''4 d''4 c''4 | bf'2. g'2. f'4 ef'4 f'4 | ef'2.~ ef'2.
\bar "|."
}
alto = { \globalParts
  \partial 2. ef'4 ef'4 ef'4 | ef'2. ef'2. bf4 bf4 bf4 | d'2.~ d'2. d'4 d'4 d'4 | d'2. d'2. bf4 bf4 bf4 | bf2.~ bf2. ef'4 ef'4 ef'4 | ef'2. ef'2. df'4 c'4 df'4 | ef'2.~ ef'2. ef'4 ef'4 ef'4 | ef'2. ef'2. bf4 bf4 bf4 | bf2.~ bf2.
}
tenor = { \globalParts
  \partial 2. bf4 af4 bf4 | c'2. bf2. g4 f4 g4 | af2.~ af2. af4 g4 af4 | bf2. af2. af4 g4 f4 | g2.~ g2. bf4 af4 bf4 | c'2. bf2. g4 g4 g4 | af2.~ af2. af4 bf4 af4 | g2. bf2. af4 g4 af4 | g2.~ g2.
}
bass = { \globalParts
  \partial 2. ef4 ef4 ef4 | ef2. ef2. ef4 ef4 ef4 | bf,2.~ bf,2. bf,4 bf,4 bf,4 | bf,2. bf,2. bf,4 bf,4 bf,4 | ef2.~ ef2. ef4 ef4 ef4 | ef2. ef2. ef4 ef4 ef4 | af,2.~ af,2. af,4 af,4 af,4 | bf,2. bf,2. bf,4 bf,4 bf,4 | ef2.~ ef2.
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l Have thine own way, Lord! Have thine own way! Thou art the pot -- ter, I am the clay. Mold me and make me aft -- er thy will, while I am wait -- ing, yield -- ed and still. 
}
verseB = \lyricmode {
Have thine own way, Lord! Have thine own way! Search me and try me, Mas -- ter, to -- day! Wash me just now, Lord, wash me just now, as in thy pres -- ence hum -- bly I bow. 
}
verseC = \lyricmode {
Have thine own way, Lord! Have thine own way! Wound -- ed and wea -- ry, help me, I pray! Pow -- er -- all pow -- er -- sure -- ly is thine! Touch me and heal me, Sav -- ior di -- vine! 
}
verseD = \lyricmode {
Have thine own way, Lord! Have thine own way! Hold o'er my be -- ing ab -- so -- lute sway! Fill with thy Spir -- it till all shall see Christ on -- ly, al -- ways, liv -- ing in me! 
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/4verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-4verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
