\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Will L. Thompson," \italic "Sparkling Gems Nos. 1 & 2," "1880" }
poet = \smallText \markup { "Text: Will L. Thompson," \italic "Sparkling Gems Nos. 1 & 2," "1880" }
meter = \smallText "THOMPSON 11 7. 11 7 with refrain"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 3
tags = "english christian 4part"
dateAdded = "2026-07-31"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Softly and tenderly Jesus is calling"
hymnKey = \key af \major
hymnTime = \time 6/8
hymnBaseMoment = \set Timing.baseMoment = #(ly:make-moment 1/8)
hymnBeatStructure = \set Timing.beatStructure = 3,3
quarternoteTempo = 68
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  c''8. bf'16 af'8 af'8 g'8 af'8 | bf'8 af'8 f'8 f'8 ef'8 r8 |
  af'8 af'8 af'8 c''8. bf'16 af'8 | bf'4.~ bf'4 r8 | \break
  c''8. bf'16 af'8 af'8 g'8 af'8 | bf'8 af'8 f'8 f'8 ef'8 r8 |
  af'8 af'8 df''8 c''8. af'16 bf'8 | af'4.~ af'4
  \bar "||" \break ef'8 | bf'4.~ bf'4 c''8 | af'4( bf'8 c''4.) |
  bf'8 bf'8 bf'8 c''16 c''8. d''8 | ef''4(\fermata d''8\fermata df''4)\fermata r8 | \break
  c''8. bf'16 af'8 af'8 g'8 af'8 | bf'8 af'8 f'8 f'8 ef'8 r8 |
  af'16 af'8. df''8c''16 af'8.\fermata bf'8\fermata | af'4.~ af'4 r8
\bar "|."
}
alto = { \globalParts
  ef'8. df'16 c'8 ef'8 df'8 c'8 | df'8 df'8 df'8 df'8 c'8 r8 | ef'8 ef'8 ef'8 d'8. d'16 d'8 | ef'4.~ ef'4 r8 | ef'8. df'16 c'8 ef'8 df'8 c'8 | df'8 df'8 df'8 df'8 c'8 r8 | ef'8 ef'8 f'8 ef'8. c'16 df'8 | c'4.~ c'4
  r8 | r4  g'8 g'4 \pa r8 | r4 \pt g'8 af'4. | \pa g'8 g'8 bf'8 \pt a'16 a'8. af'8 | g'4(\fermata af'8\fermata bf'4)\fermata r8 | ef'8. df'16 c'8 ef'8 df'8 c'8 | df'8 df'8 df'8 df'8 c'8 r8 | ef'16 ef'8. f'8ef'16 c'8.\fermata df'8\fermata | c'4.~ c'4 r8
}
tenor = { \globalParts
  af8. af16 af8 af8 ef8 ef8 | f8 f8 af8 af8 af8 r8 | c'8 c'8 c'8 af8. af16 bf8 | g4.~ g4 r8 | af8. af16 af8 af8 ef8 ef8 | f8 f8 af8 af8 af8 r8 | af8 af8 af8 af8. af16 g8 | af4.~ af4 r8 | r4 df'8 df'4 \pa ef'8 | c'4 \pt ef'8 ef'4. | ef'8 ef'8 ef'8 \pa ef'16 ef'8. bf8 \pt | bf4(\fermata bf8\fermata ef'4)\fermata r8 | af8. af16 af8 af8 ef8 ef8 | f8 f8 af8 af8 af8 r8 | af16 af8. af8af16 af8.\fermata g8\fermata | af4.~ af4 r8
}
bass = { \globalParts
  af,8. af,16 af,8 c8 bf,8 af,8 | df8 df8 df8 af,8 af,8 r8 | af8 af8 af8 f8. f16 f8 | ef4.~ ef4 r8 | af,8. af,16 af,8 c8 bf,8 af,8 | df8 df8 df8 af,8 af,8 r8 | c8 c8 df8 ef8. ef16 ef8 | af,4.~ af,4 r8 | r4 ef8 ef4 r8 | r4 ef8 af4. | bf8 bf8 g8 f16 f8. bf8 | ef4(\fermata f8\fermata g4)\fermata r8 | af,8. af,16 af,8 c8 bf,8 af,8 | df8 df8 df8 af,8 af,8 r8 | c16 c8. df8ef16 ef8.\fermata ef8\fermata | af,4.~ af,4 r8
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

%% The page sets a second text line between the staves in the refrain, sung by
%% an echo voice the source stems separately on both staves. Reduced to four
%% parts it rides the tenor. The source only encoded the first "come"; the rest
%% is what the page prints. Skips carry it past every other note.
tenorRefrain = \lyricmode {
  _ _ _ _ _ _
  _ _ _ _ _
  _ _ _ _ _ _
  _
  _ _ _ _ _ _
  _ _ _ _ _
  _ _ _ _ _ _
  _
  come home,
  _ _
  Come home!
}

verseA = \lyricmode {
\l Soft -- ly and ten -- der -- ly Je -- sus is call -- ing,
\l call -- ing for you and for me.
\l See, on the por -- tals he's wait -- ing and watch -- ing,
\l watch -- ing for you and for me.
  %% CHORUS
\l ''Come home, come home!
\l You who are wea -- ry, come home.''
\l Ear -- nest -- ly, ten -- der -- ly, Je -- sus is call -- ing,
\l call -- ing, ''O sin -- ner, come home!''
  %% END CHORUS
}
verseB = \lyricmode {
\l Why should we tar -- ry when Je -- sus is plead -- ing,
\l plead -- ing for you and for me?
\l Why should we lin -- ger and heed not his mer -- cies,
\l mer -- cies for you and for me.
  %% CHORUS
  \SB {
    ''Come home, come home!
    You who are wea -- ry, come home.''
    Ear -- nest -- ly, ten -- der -- ly, Je -- sus is call -- ing,
    call -- ing, ''O sin -- ner, come home!''
  }
  %% END CHORUS
}
verseC = \lyricmode {
\l Oh, for the won -- der -- ful love he has prom -- ised,
\l prom -- ised for you and for me!
\l Though we have sinned he has mer -- cy and par -- don,
\l par -- don for you and for me.
  %% CHORUS
  \SC {
    ''Come home, come home!
    You who are wea -- ry, come home.''
    Ear -- nest -- ly, ten -- der -- ly, Je -- sus is call -- ing,
    call -- ing, ''O sin -- ner, come home!''
  }
  %% END CHORUS
}



% Set up music-aligned verses. Inlined rather than \include "3verse.ily" for
% two reasons: the tenor echo needs its own Lyrics context, and the verse
% text hangs on the alto. The soprano carries the tune wherever it sings,
% but it rests through the refrain's opening call ("Come home, come home!",
% m9-m12) and only rejoins at "Ear-nest-ly"; the alto is the one treble
% line sounding in every measure, so it is what the syllables can align to.
all_verses = <<
  \new NullVoice = "soprano" {\removeWithTag #'midionly \soprano}
  \new NullVoice = "tenor" {\removeWithTag #'midionly \tenor}
  \tag #'verseA { \new Lyrics  \lyricsto soprano  { \globalLyrics "1" "" \verseA } }
  \tag #'verseB { \new Lyrics  \lyricsto soprano  { \globalLyrics "2" "" \verseB } }
  \tag #'verseC { \new Lyrics  \lyricsto soprano  { \globalLyrics "3" "" \verseC } }
  \new Lyrics  \lyricsto tenor  { \globalLyrics "" "" \tenorRefrain }
>>

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-3verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
