\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
%% The poet line is split across two lines because on one line the two
%% attributions overran the margin and collided into each other
%% ("...Revival Music,M1876c: Edmund S. Lorenz..."). Only the poet is
%% split: meter sits below poet in the header, so making the composer two
%% lines as well pushes the meter line down onto the top staff. The
%% composer fits on one line, so it stays there - the same split
%% a-mighty-fortress-is-our-god uses.
%%
%% The hymnal sets the source titles in italic, but \twoLineSmallText
%% takes plain strings, so the italics are given up to keep the credits
%% legible and inside the margin.
composer = \smallText \markup { "Music: Edmund S. Lorenz," \italic "Notes of Triumph: for the Sunday School," "1886" }
poet = \twoLineSmallText "Text: anonymous, attributed to Howard Kingsbury," "Complete Compendium of Revival Music, 1876"
meter = \smallText "GOD IS LOVE 83.83.8884 with refrain"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 3
tags = "english christian 4part"
dateAdded = "2026-07-25"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Come, let us all unite to sing"
hymnKey = \key d \major
hymnTime = \time 2/2
quarternoteTempo = 150
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  \time 2/2 d'4 fs'8 g'8 a'4 a'4 | b'4 cs''4 d''2 | e''2 cs''2 | d''2. r4 | d'4 fs'8 g'8 a'4 a'4 | b'4 cs''4 d''2 | cs''2 b'2 | a'2. r4 | g'4 g'8 fs'8 e'4 g'4 | fs'4 d''4 a'2 | g'4 g'8 fs'8 e'4 g'4 | fs'4 d''4 a'2 | d''4 d''8 d''8 d''4 d''4 | e''4 d''4 cs''4 b'4 | a'2 cs''2 | d''2. r4 | a'2 b'2 | g'2. r4 | g'2 a'2 | fs'2. r4 | d''4 d''8 d''8 d''4 d''4 | e''4 d''4 cs''4 b'4 | a'2 cs''2 | d''2.
\bar "|."
}
alto = { \globalParts
  %% Final measure ends on the dotted half, with no trailing r4. The source
  %% does carry one - every voice's last measure is "dotted half + quarter
  %% rest" - but the converter kept it only in alto and bass and dropped it
  %% in soprano and tenor, so the score showed a quarter rest hanging off
  %% two of the four voices after the closing chord. Dropped here to match.
  \time 2/2 d'4 d'8 e'8 fs'4 fs'4 | g'4 g'4 fs'2 | g'2 e'2 | fs'2. r4 | d'4 d'8 e'8 fs'4 fs'4 | g'4 g'4 fs'2 | e'2 d'2 | cs'2. r4 | e'4 e'8 d'8 cs'4 e'4 | d'4 fs'4 fs'2 | e'4 e'8 d'8 cs'4 e'4 | d'4 fs'4 fs'2 | fs'4 fs'8 g'8 a'4 fs'4 | g'4 g'4 g'4 g'4 | fs'2 g'2 | fs'2. r4 | fs'2 g'2 | e'2. r4 | e'2 fs'2 | d'2. r4 | fs'4 fs'8 g'8 a'4 fs'4 | g'4 g'4 g'4 g'4 | fs'2 g'2 | fs'2.
}
tenor = { \globalParts
  %% m16-m20 were malformed: the converter emitted "a2. r1 | r4" and
  %% "a4 a4 a4 r1 | r4", splitting whole rests across the barline so m16
  %% ran to 7 beats and the leftover quarter formed a measure of its own.
  %% The durations still summed correctly overall, so LilyPond compiled it
  %% without a barcheck warning - it is only wrong to look at and to sing.
  %%
  %% The cause is that voice 6 is empty in the source: there is no separate
  %% tenor part. The tenor is the upper note of the bass-staff chords in
  %% voice 5, so it carries the bass's rhythm exactly, and the corrected
  %% bars below are that rhythm (this is the "4 implied notes restored"
  %% warning from the conversion).
  \time 2/2 fs4 a8 a8 d'4 d'4 | d'4 a4 a2 | b2 a2 | a2. r4 | fs4 a8 a8 d'4 d'4 | d'4 a4 a2 | a2 gs2 | a2. r4 | a,1 | d,1 | a,1 | d,1 | a4 a8 a8 a4 a4 | b4 b4 cs'4 d'4 | d'2 a2 | a2. r4 | r1 | a4 a4 a4 r4 | r1 | a4 a4 a4 r4 | a4 a8 a8 a4 a4 | b4 b4 cs'4 d'4 | d'2 a2 | a2.
}
bass = { \globalParts
  %% Trailing r4 dropped from the final measure - see the note on alto.
  \time 2/2 d4 d8 d8 d4 d4 | g4 e4 d2 | g2 a2 | d2. r4 | d4 d8 d8 d4 d4 | g4 e4 d2 | e2 e2 | a,2. r4 | a,1 | d,1 | a,1 | d,1 | d4 d8 e8 fs4 d4 | g4 g4 g4 g4 | a2 a,2 | d2. r4 | r1 | a,4 a,4 a,4 r4 | r1 | d4 d4 d4 r4 | d4 d8 e8 fs4 d4 | g4 g4 g4 g4 | a2 a,2 | d2.
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

%% Verse is m1-16; the refrain is m17-24, which the page marks "Refrain"
%% after a double bar and the meter records as "with refrain". The
%% converter had no way to see that: it reads syllables off the soprano
%% line in order, so the refrain arrived attached to verse 1 and verses
%% 2-3 simply ran out of words at m16. Wrapping it in \SB and \SC gives
%% the later verses their copy for the slides while the score still
%% prints it once, following when-israel-was-in-egypts-land.
verseA = \lyricmode {
\l Come, let us all u -- nite to sing, God is love.
\l Let heav'n and earth their prais -- es bring, God is love.
\l Let ev -- 'ry soul from sin a -- wake,
\l let ev -- 'ry heart sweet mu -- sic make,
\l and sing with us for Je -- sus' sake, for God is love.
%% REFRAIN
\l God is love! God is love!
\l Come, let us all u -- nite to sing that God is love!
}
verseB = \lyricmode {
\l O tell to earth's re -- mot -- est bound, God is love.
\l In Christ we have re -- demp -- tion found, God is love.
\l His blood has washed our sins a -- way,
\l his Spir -- it turned our night to day,
\l and now we can re -- joice to say that God is love.
%% REFRAIN
\SB {
\l God is love! God is love!
\l Come, let us all u -- nite to sing that God is love!
}
}
verseC = \lyricmode {
\l How hap -- py is our por -- tion here, God is love.
\l His prom -- is -- es our spir -- its cheer, God is love.
\l He is our sun and shield by day,
\l our help, our hope, our strength and stay;
\l he will be with us all the way, our God is love.
%% REFRAIN
\SC {
\l God is love! God is love!
\l Come, let us all u -- nite to sing that God is love!
}
}

%% The refrain is antiphonal: the lower voices answer "God is love!" in
%% m18 and m20 while the upper voices hold, then join them wordlessly for
%% m21-24 under the soprano text above. The source carries that answer as
%% its own lyric line on voice 5, but the converter assigns every syllable
%% to the soprano, so it was dropped. Restored here on its own staff,
%% following warm-summer-sun.
%%
%% The 38 skips are note events in the bass line before m18, not measures.
%% Do not re-derive this by counting sounding notes and assuming rests are
%% free: that gives 37 and puts "God" a note early, splitting it from "is"
%% across m17's rest. The count was settled by rendering 36-40 and reading
%% the engraved x-positions - at 38 the two answers come out contiguous
%% (God/is/love! at 27/32/34 and 47/52/55), and every other value leaves a
%% visible gap inside one of them.
%%
%% Only the first answer needs padding. The second follows three notes
%% later on its own, because m19's rest does not take a syllable the way
%% m17's does.
bottomA = \lyricmode {
\repeat unfold 38 { \skip 1 }
\l God is love!
\l God is love!
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/3verse.ily"

%% Defined after the include: 3verse.ily sets all_verses, and this adds the
%% bass answer as a second lyric staff without disturbing it.
bottom_verses = <<
  \new NullVoice = "bass" {\removeWithTag #'midionly \bass}
  \new Lyrics \lyricsto bass { \globalLyrics "" "" \bottomA }
>>

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-3verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
