\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Edmund S. Lorenz," \italic "Notes of Triumph: for the Sunday School," "1886" }
poet = \smallText \markup { "Text: anonymous, attributed to Howard Kingsbury," \italic "Complete Compendium of Revival Music," "1876" }
meter = \smallText "GOD IS LOVE 83.83.8884 with refrain"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 3
tags = "english christian 4part"
dateAdded = "2026-07-25"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Come, let us all unite to sing"
hymnKey = \key d \major
hymnTime = \time 2/2
quarternoteTempo = 150
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  \time 2/2 d'4 fs'8 g'8 a'4 a'4 | b'4 cs''4 d''2 | e''2 cs''2 | d''2. r4 | d'4 fs'8 g'8 a'4 a'4 | b'4 cs''4 d''2 | cs''2 b'2 | a'2. r4 | g'4 g'8 fs'8 e'4 g'4 | fs'4 d''4 a'2 | g'4 g'8 fs'8 e'4 g'4 | fs'4 d''4 a'2 | d''4 d''8 d''8 d''4 d''4 | e''4 d''4 cs''4 b'4 | a'2 cs''2 | d''2. r4 | a'2 b'2 | g'2. r4 | g'2 a'2 | fs'2. r4 | d''4 d''8 d''8 d''4 d''4 | e''4 d''4 cs''4 b'4 | a'2 cs''2 | d''2.
\bar "|."
}
alto = { \globalParts
  \time 2/2 d'4 d'8 e'8 fs'4 fs'4 | g'4 g'4 fs'2 | g'2 e'2 | fs'2. r4 | d'4 d'8 e'8 fs'4 fs'4 | g'4 g'4 fs'2 | e'2 d'2 | cs'2. r4 | e'4 e'8 d'8 cs'4 e'4 | d'4 fs'4 fs'2 | e'4 e'8 d'8 cs'4 e'4 | d'4 fs'4 fs'2 | fs'4 fs'8 g'8 a'4 fs'4 | g'4 g'4 g'4 g'4 | fs'2 g'2 | fs'2. r4 | fs'2 g'2 | e'2. r4 | e'2 fs'2 | d'2. r4 | fs'4 fs'8 g'8 a'4 fs'4 | g'4 g'4 g'4 g'4 | fs'2 g'2 | fs'2. r4
}
tenor = { \globalParts
  \time 2/2 fs4 a8 a8 d'4 d'4 | d'4 a4 a2 | b2 a2 | a2. r4 | fs4 a8 a8 d'4 d'4 | d'4 a4 a2 | a2 gs2 | a2. r4 | a,1 | d,1 | a,1 | d,1 | a4 a8 a8 a4 a4 | b4 b4 cs'4 d'4 | d'2 a2 | a2. r1 | r4 | a4 a4 a4 r1 | r4 | a4 a4 a4 r4 | a4 a8 a8 a4 a4 | b4 b4 cs'4 d'4 | d'2 a2 | a2.
}
bass = { \globalParts
  \time 2/2 d4 d8 d8 d4 d4 | g4 e4 d2 | g2 a2 | d2. r4 | d4 d8 d8 d4 d4 | g4 e4 d2 | e2 e2 | a,2. r4 | a,1 | d,1 | a,1 | d,1 | d4 d8 e8 fs4 d4 | g4 g4 g4 g4 | a2 a,2 | d2. r4 | r1 | a,4 a,4 a,4 r4 | r1 | d4 d4 d4 r4 | d4 d8 e8 fs4 d4 | g4 g4 g4 g4 | a2 a,2 | d2. r4
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l Come, let us all u -- nite to sing, God is love. Let heav'n and earth their prais -- es bring, God is love. Let ev -- 'ry soul from sin a -- wake, let ev -- 'ry heart sweet mu -- sic make, and sing with us for Je -- sus' sake, for God is love. God is love! God is love! God is love! God is love! Come, let us all u -- nite to sing that God is love! 
}
verseB = \lyricmode {
O tell to earth's re -- mot -- est bound, God is love. In Christ we have re -- demp -- tion found, God is love. His blood has washed our sins a -- way, his Spir -- it turned our night to day, and now we can re -- joice to say that God is love. 
}
verseC = \lyricmode {
How hap -- py is our por -- tion here, God is love. His prom -- is -- es our spir -- its cheer, God is love. He is our sun and shield by day, our help, our hope, our strength and stay; he will be with us all the way, our God is love. 
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/3verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-3verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
