\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Chester G. Allen," \italic "Bright Jewels for the Sunday School," "1869" }
poet = \smallText \markup { "Text: Fanny J. Crosby," \italic "Bright Jewels for the Sunday School," "1869" }
meter = \smallText "ALLEN 12 10. 12 10. 11 10 with refrain"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 3
tags = "english christian 4part"
dateAdded = "2026-08-02"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Praise him, praise him"
hymnKey = \key g \major
hymnTime = \time 6/8
hymnBaseMoment = \set Timing.baseMoment = #(ly:make-moment 1/8)
hymnBeatStructure = \set Timing.beatStructure = 3,3
quarternoteTempo = 128
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

%% One system per poetic line: the meter is 12 10. 12 10. 11 10, so the verse
%% is six lines over m1-24 and the refrain is the last two over m25-32. The
%% source's backward repeat returns for the refrain, not for the next stanza.
soprano = { \globalParts
  b'4. d''4. | g'4. b'4. | a'8 b'8 a'8 g'8 fs'8 e'8 | d'4. g'4. \break
  | b'4. d''4. | g'4. b'4. | b'8 a'8 g'8 a'4 b'8 | a'4.~ a'4 r8 \break
  | b'4. d''4. | g'4. b'4. | a'8 b'8 a'8 g'8 fs'8 e'8 | d'4. g'4. \break
  | b'4. d''4. | c''4. a'4. | g'8 fs'8 g'8 b'4 a'8 | g'4.~ g'4 r8 \break
  | a'4. b'4. | a'4( fs'8) d'4. | c''8 b'8 a'8 b'4 c''8 | b'4. a'4. \break
  | b'4. d''4. | g'4. b'4. | b'8 a'8 g'8 a'4 b'8 | a'4.~ a'4 r8 \bar "||" \break
  | b'4. d''4. | g'4. b'4. | a'8 b'8 a'8 g'8 fs'8 e'8 | d'4. g'4. \break
  | b'4. d''4. | c''4. a'4. | g'8 fs'8 g'8 b'4 a'8 | g'4.~ g'4
\bar "|."
}
alto = { \globalParts
  d'4. d'4. | d'4. d'4. | e'8 e'8 e'8 e'8 d'8 c'8 | b4. b4. | d'4. d'4. | b4. d'4. | cs'8 cs'8 cs'8 cs'4 cs'8 | d'4.~ d'4 r8 | d'4. d'4. | d'4. d'4. | e'8 e'8 e'8 e'8 d'8 c'8 | b4. b4. | d'4. f'4. | e'4. e'4. | d'8 d'8 d'8 g'4 fs'8 | g'4.~ g'4 r8 | d'4. d'4. | d'4. d'4. | d'8 d'8 d'8 d'4 d'8 | d'4. d'4. | d'4. d'4. | b4. b4. | cs'8 cs'8 cs'8 cs'4 cs'8 | d'4.~ d'4 r8 | d'4. d'4. | d'4. d'4. | e'8 e'8 e'8 e'8 d'8 c'8 | b4. b4. | d'4. f'4. | e'4. e'4. | d'8 d'8 d'8 g'4 fs'8 | g'4.~ g'4 r8
}
tenor = { \globalParts
  g4. b4. | b4. g4. | c'8 c'8 c'8 g8 g8 g8 | g4. g4. | g4. g4. | g4. g4. | g8 g8 g8 e4 g8 | fs4.~ fs4 r8 | g4. b4. | b4. g4. | c'8 c'8 c'8 g8 g8 g8 | g4. g4. | g4. g4. | g4. c'4. | b8 a8 b8 d'4 c'8 | b4.~ b4 r8 | fs4. g4. | fs4( a8) fs4. | a8 g8 fs8 g4 a8 | g4. fs4. | g4. g4. | g4. g4. | g8 g8 g8 e4 g8 | fs4.~ fs4 r8 | g4. b4. | b4. g4. | c'8 c'8 c'8 g8 g8 g8 | g4. g4. | g4. g4. | g4. c'4. | b8 a8 b8 d'4 c'8 | b4.~ b4
}
bass = { \globalParts
  g4. g4. | g4. g4. | c8 c8 c8 c8 c8 c8 | g,4. g,4. | g,4. b,4. | e4. e4. | a,8 a,8 a,8 a,4 a,8 | d4.~ d4 r8 | g4. g4. | g4. g4. | c8 c8 c8 c8 c8 c8 | g,4. g,4. | g,4. b,4. | c4. c4. | d8 d8 d8 d4 d8 | g4.~ g4 r8 | d4. d4. | d4. d4. | d8 d8 d8 d4 d8 | d4. d4. | g,4. b,4. | e4. e4. | a,8 a,8 a,8 a,4 a,8 | d4.~ d4 r8 | g4. g4. | g4. g4. | c8 c8 c8 c8 c8 c8 | g,4. g,4. | g,4. b,4. | c4. c4. | d8 d8 d8 d4 d8 | g4.~ g4 r8
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l Praise him, praise him! Je -- sus, our bless -- ed Re -- deem -- er!
\l Sing, O earth, his won -- der -- ful love pro -- claim!
\l Hail him, hail him! high -- est arch -- an -- gels in glo -- ry!
\l Strength and hon -- or give to his ho -- ly name!
\l Like a shep -- herd, Je -- sus will guard his chil -- dren.
\l In his arms he car -- ries them all day long.
  %% CHORUS
%% Same words in every verse, so the printed score shows the chorus once,
%% under verse 1; verses 2-3 pass 22 skips to stay note-aligned and carry
%% the text under \SB / \SC, which is slidesOnly. See blessed-assurance.
\l Praise him! praise him! tell of his ex -- cel -- lent great -- ness.
\l Praise him! praise him! ev -- er in joy -- ful song.
  %% END CHORUS
}
verseB = \lyricmode {
\l Praise him, praise him! Je -- sus, our bless -- ed Re -- deem -- er!
\l For our sins he suf -- fered and bled and died.
\l He our rock, our hope of e -- ter -- nal sal -- va -- tion,
\l hail him, hail him! Je -- sus, the cru -- ci -- fied.
\l Sound his prais -- es, Je -- sus who bore our sor -- rows,
\l love un -- bound -- ed, won -- der -- ful, deep, and strong.
  %% CHORUS
  \SB {
    Praise him! praise him! tell of his ex -- cel -- lent great -- ness.
    Praise him! praise him! ev -- er in joy -- ful song.
  } \SO {
    _ _ _ _ _ _ _ _ _ _ _ _
    _ _ _ _ _ _ _ _ _ _
  }
  %% END CHORUS
}
verseC = \lyricmode {
\l Praise him, praise him! Je -- sus, our bless -- ed Re -- deem -- er!
\l Heav'n -- ly por -- tals loud with ho -- san -- nas ring!
\l Je -- sus, Sav -- ior, reign -- eth for -- ev -- er and ev -- er!
\l Crown him, crown him! proph -- et, and priest, and King!
\l Christ is com -- ing, o -- ver the world vic -- to -- rious.
\l Pow'r and glo -- ry un -- to the Lord be -- long.
  %% CHORUS
  \SC {
    Praise him! praise him! tell of his ex -- cel -- lent great -- ness.
    Praise him! praise him! ev -- er in joy -- ful song.
  } \SO {
    _ _ _ _ _ _ _ _ _ _ _ _
    _ _ _ _ _ _ _ _ _ _
  }
  %% END CHORUS
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/3verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-3verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
