\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Composer," \italic "Book," "year" }
poet = \smallText \markup { "Text: Author," \italic "Book," "year" }
meter = \smallText "TUNE NAME meter"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 4
tags = "english christian 4part"
dateAdded = "2026-07-26"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Of the Father's love begotten"
hymnKey = \key ef \major
hymnTime = \time 12/4
quarternoteTempo = 120
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  ef'4 f'4 g'4 af'4 g'4 f'4 g'4( f'4) ef'1 | g'4 af'4 bf'4 c''4 bf'4( g'4) af'4 bf'1 | c''4 d''4 ef''4 bf'4 bf'4 af'4 g'4( f'4) ef'1 | c'4 d'4 ef'4 f'4 ef'4( c'4) d'4 ef'1 | ef'4 f'4 g'4 af'4 g'4 f'4 bf'4( c''4 bf'4 g'4 af'4) bf'1 | ef'4 d'4 c'4 d'4 ef'4 c'4 bf1 | ef'4 f'4 g'4 bf'4 g'4 ef'4 f'2( ef'1)
\bar "|."
}
alto = { \globalParts
}
tenor = { \globalParts
}
bass = { \globalParts
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l Of the Fa -- ther's love be -- got -- ten, ere the worlds be -- gan to be, he is Al -- pha and O me -- ga, he the Source the End -- ing he, of the things that are and have been, and the fu -- ture years shall see, ev -- er -- more and ev -- er -- more! 
}
verseB = \lyricmode {
By his word was all cre -- at -- ed. He com -- mand -- ed and 'twas done. Earth and sky and bound -- less o -- cean, u -- ni -- verse of Three -- in -- One. All that sees the moon's soft ra -- diance, all that breathes be -- neath the sun, ev -- er -- more and ev -- er -- more! 
}
verseC = \lyricmode {
This is he whom seers in old time chant -- ed of with one ac -- cord, whom the voic -- es of the proph -- ets prom -- ised in their faith -- ful word. Now he shines, the long -- ex -- pect -- ed. Let cre -- a -- tion praise its Lord, ev -- er -- more and ev -- er -- more! 
}
verseD = \lyricmode {
O ye heights of heav'n a -- dore him, an -- gel hosts, his prais -- es sing. Pow'rs, do -- min -- ions, fall be -- fore him, and ex -- tol our God and King. Let no tongue on earth keep si -- lent, ev -- 'ry voice in con -- cert ring, ev -- er -- more and ev -- er -- more! 
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/4verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-4verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
