\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Plainsong, 13th c.," \italic "Piae Cantiones," "1582" }
poet = \twoLineSmallText \markup { "Text: Aurelius Clemens Prudentius," \italic "Corde natus ex Parentis;" } \markup { "tr. John M. Neale, 1851, and Henry W. Baker, 1861" }
meter = \smallText "DIVINUM MYSTERIUM 87. 87. 877"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 4
tags = "english christian winter 1part chant"
dateAdded = "2026-07-26"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Of the Father's love begotten"
hymnKey = \key ef \major
hymnTime = \time 12/4
quarternoteTempo = 120
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

%% Plainsong, so the hymnal prints no time signature and the barlines are
%% phrase divisions rather than measures of equal length. The converter
%% declared 12/4 from the source and four of the seven phrases do not fit
%% it - m2 and m4 are 11/4, m5 is 15/4, m6 is 10/4 - which is four failed
%% barchecks, not four wrong phrases. \cadenzaOn stops LilyPond counting
%% altogether, which is what unmetered chant wants: the barlines below
%% then fall exactly where the hymnal draws them, and \break puts
%% one phrase pair per system as printed.
%%
%% hymnTime stays 12/4 for the MIDI tempo to key off; the signature is
%% hidden rather than removed, following o-come-o-come-immanuel.
soprano = { \globalParts
  \override Staff.TimeSignature #'stencil = ##f
  \cadenzaOn
  ef'4 f'4 g'4 af'4 g'4 f'4 g'4( f'4) ef'1 \bar "|"
  g'4 af'4 bf'4 c''4 bf'4( g'4) af'4 bf'1 \bar "|" \break
  c''4 d''4 ef''4 bf'4 bf'4 af'4 g'4( f'4) ef'1 \bar "|"
  c'4 d'4 ef'4 f'4 ef'4( c'4) d'4 ef'1 \bar "|" \break
  ef'4 f'4 g'4 af'4 g'4 f'4 bf'4( c''4 bf'4 g'4 af'4) bf'1 \bar "|"
  ef'4 d'4 c'4 d'4 ef'4 c'4 bf1 \bar "|" \break
  ef'4 f'4 g'4 bf'4 g'4 ef'4 f'2( ef'1)
\bar "|."
}
%% Unison plainsong: the variables must exist because
%% lib/traditional-book.ily references them, but only soprano sings.
alto = {}
tenor = {}
bass = {}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l Of the Fa -- ther's love be -- got -- ten, ere the worlds be -- gan to be, he is Al -- pha and O me -- ga, he the Source the End -- ing he, of the things that are and have been, and the fu -- ture years shall see, ev -- er -- more and ev -- er -- more! 
}
verseB = \lyricmode {
By his word was all cre -- at -- ed. He com -- mand -- ed and 'twas done. Earth and sky and bound -- less o -- cean, u -- ni -- verse of Three -- in -- One. All that sees the moon's soft ra -- diance, all that breathes be -- neath the sun, ev -- er -- more and ev -- er -- more! 
}
verseC = \lyricmode {
This is he whom seers in old time chant -- ed of with one ac -- cord, whom the voic -- es of the proph -- ets prom -- ised in their faith -- ful word. Now he shines, the long -- ex -- pect -- ed. Let cre -- a -- tion praise its Lord, ev -- er -- more and ev -- er -- more! 
}
verseD = \lyricmode {
O ye heights of heav'n a -- dore him, an -- gel hosts, his prais -- es sing. Pow'rs, do -- min -- ions, fall be -- fore him, and ex -- tol our God and King. Let no tongue on earth keep si -- lent, ev -- 'ry voice in con -- cert ring, ev -- er -- more and ev -- er -- more! 
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/4verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-4verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
