\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Composer," \italic "Book," "year" }
poet = \smallText \markup { "Text: Author," \italic "Book," "year" }
meter = \smallText "TUNE NAME meter"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 5
tags = "english christian 4part"
dateAdded = "2026-07-27"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "My hope is built on nothing less"
hymnKey = \key g \major
hymnTime = \time 3/4
quarternoteTempo = 100
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  \partial 4 d'4 | g'8 b'8 d''4 b'4 | b'8 a'8 a'4 b'4 | c''8 c''8 c''4 a'4 | g'8 fs'8 g'4 d'4 | g'8 b'8 d''4 b'4 | b'8 a'8 a'4 b'4 | c''8 c''8 c''4 a'4 | g'8 fs'8 g'4 | d''4 | d''8 d''8 d''4 d''4 | e''8 e''8 e''4 e''4 | d''8 b'8 b'4 g'4 | b'8 b'8 a'4 d'4 | g'8 g'8 g'4 b'4 | a'8 a'8 g'4
\bar "|."
}
alto = { \globalParts
  \partial 4 d'4 | d'8 d'8 g'4 g'4 | g'8 fs'8 fs'4 g'4 | g'8 g'8 g'4 e'4 | d'8 d'8 d'4 d'4 | d'8 d'8 g'4 g'4 | g'8 fs'8 fs'4 g'4 | g'8 g'8 g'4 e'4 | d'8 d'8 d'4 | g'4 | g'8 fs'8 g'4 g'4 | g'8 g'8 g'4 g'4 | g'8 d'8 d'4 d'4 | d'8 d'8 d'4 d'4 | d'8 b8 e'4 d'4 | d'8 d'8 b4
}
tenor = { \globalParts
  \partial 4 d4 | b8 b8 b4 d'4 | d'8 d'8 d'4 d'4 | e'8 e'8 e'4 c'4 | b8 a8 b4 d4 | b8 b8 b4 d'4 | d'8 d'8 d'4 d'4 | e'8 e'8 e'4 c'4 | b8 a8 b4 | b4 | b8 c'8 d'4 b4 | c'8 c'8 c'4 c'4 | b8 g8 g4 b4 | g8 g8 fs4 fs4 | g8 g8 g4 g4 | g8 fs8 g4
}
bass = { \globalParts
  \partial 4 d4 | g8 g8 g4 g4 | d8 d8 d4 g4 | c8 c8 c4 c4 | d8 d8 g4 d4 | g8 g8 g4 g4 | d8 d8 d4 g4 | c8 c8 c4 c4 | d8 d8 g4 | g4 | g8 a8 b4 g4 | c8 c8 c4 c4 | g8 g8 g4 g4 | g,8 b,8 d4 d4 | b,8 g,8 c4 g,4 | d8 d8 g,4
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l My hope is built on noth -- ing less than Je -- sus' blood and right -- eous -- ness. I dare not trust the sweet -- est frame, but whol -- ly lean on Je -- sus' name. On Christ, the sol -- id rock, I stand; all oth -- er ground is sink -- ing sand, all oth -- er ground is sink -- ing sand. 
}
verseB = \lyricmode {
When dark -- ness veils his lov -- ing face, I rest up -- on un -- chang -- ing grace. In ev -- 'ry rough and storm -- y gale, my an -- chor holds with -- in the vale. 
}
verseC = \lyricmode {
His oath, his cov -- e -- nant, and blood, sup -- port me in the 'whelm -- ing flood. When all a -- round my soul gives way, he then is all my hope and stay. 
}
verseD = \lyricmode {
Not earth, nor hell, my soul can move; I rest up -- on un -- chang -- ing love. I trust his right -- eous char -- ac -- ter, his coun -- sel, prom -- ise, and his pow'r. 
}
verseE = \lyricmode {
When he shall come with trum -- pet sound, oh, may I then in him be found, dressed in his right -- eous -- ness a -- lone, fault -- less to stand be -- fore the throne. 
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/5verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-5verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
