\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: William B. Bradbury, 1863," \italic "Devotional Hymn and Tune Book," "1864" }
poet = \smallText \markup { "Text: Edward Mote, ca. 1834," \italic "Spiritual Magazine," "alt." }
meter = \smallText "SOLID ROCK LM with refrain"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 5
tags = "english christian 4part"
dateAdded = "2026-07-27"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "My hope is built on nothing less"
hymnKey = \key g \major
hymnTime = \time 3/4
quarternoteTempo = 100
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

%% Four systems, as the page prints them: the verse is m1-9 and the
%% refrain m10-16, with the standalone d''4 of m10 as the refrain's
%% pickup. The source marks m9 barline light-light (dropped by the
%% converter), but the verse/refrain division falls on a system break
%% here, where LilyPond draws the line-end bar and suppresses a mid-staff
%% double bar - so \bb alone carries it, as it does on the page.
%%
%% The page also prints "Refrain" over m10 (source m10 <words>Refrain</words>,
%% also dropped), but no song in this repo marks one on the staff - the
%% convention here is to say "with refrain" in the meter string, as
%% blessed-assurance and jesus-loves-me do, and let the lyrics carry it.
%% The tune line on the page says the same: "SOLID ROCK LM with refrain".
%%
%% The source's backward repeat at m16 is a MuseScore artifact for "sing
%% the next stanza"; this repo expands stanzas as verseA-E, so it is not
%% a volta and is deliberately not reproduced.
soprano = { \globalParts
  \partial 4 d'4 | g'8 b'8 d''4 b'4 | b'8 a'8 a'4 b'4 | c''8 c''8 c''4 a'4 | g'8 fs'8 g'4 d'4 \bb | g'8 b'8 d''4 b'4 | b'8 a'8 a'4 b'4 | c''8 c''8 c''4 a'4 | g'8 fs'8 g'4 \bb d''4 | d''8 d''8 d''4 d''4 | e''8 e''8 e''4 e''4 | d''8 b'8 b'4 g'4 | b'8 b'8 a'4 d'4 | g'8 g'8 g'4 b'4 | a'8 a'8 g'4
\bar "|."
}
alto = { \globalParts
  \partial 4 d'4 | d'8 d'8 g'4 g'4 | g'8 fs'8 fs'4 g'4 | g'8 g'8 g'4 e'4 | d'8 d'8 d'4 d'4 \bb | d'8 d'8 g'4 g'4 | g'8 fs'8 fs'4 g'4 | g'8 g'8 g'4 e'4 | d'8 d'8 d'4 \bb g'4 | g'8 fs'8 g'4 g'4 | g'8 g'8 g'4 g'4 | g'8 d'8 d'4 d'4 | d'8 d'8 d'4 d'4 | d'8 b8 e'4 d'4 | d'8 d'8 b4
}
tenor = { \globalParts
  \partial 4 d4 | b8 b8 b4 d'4 | d'8 d'8 d'4 d'4 | e'8 e'8 e'4 c'4 | b8 a8 b4 d4 \bb | b8 b8 b4 d'4 | d'8 d'8 d'4 d'4 | e'8 e'8 e'4 c'4 | b8 a8 b4 \bb b4 | b8 c'8 d'4 b4 | c'8 c'8 c'4 c'4 | \pa b8 g8 \pt g4 b4 | g8 g8 fs4 fs4 | g8 g8 g4 g4 | g8 fs8 g4
}
bass = { \globalParts
  \partial 4 d4 | g8 g8 g4 g4 | d8 d8 d4 g4 | c8 c8 c4 c4 | d8 d8 g4 d4 \bb | g8 g8 g4 g4 | d8 d8 d4 g4 | c8 c8 c4 c4 | d8 d8 g4 \bb g4 | g8 a8 b4 g4 | c8 c8 c4 c4 | g8 g8 g4 g4 | g,8 b,8 d4 d4 | b,8 g,8 c4 g,4 | d8 d8 g,4
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l My hope is built on noth -- ing less than Je -- sus' blood and right -- eous -- ness.
\l I dare not trust the sweet -- est frame, but whol -- ly lean on Je -- sus' name.
  %% CHORUS
\l On Christ, the sol -- id rock, I stand; all oth -- er ground is sink -- ing sand,
\l all oth -- er ground is sink -- ing sand.
  %% END CHORUS
}
verseB = \lyricmode {
\l When dark -- ness veils his lov -- ing face, I rest up -- on un -- chang -- ing grace.
\l In ev -- 'ry rough and storm -- y gale, my an -- chor holds with -- in the vale.
  %% CHORUS
  \SB {
    On Christ, the sol -- id rock, I stand; all oth -- er ground is sink -- ing sand,
    all oth -- er ground is sink -- ing sand.
  } \SO {
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    _ _ _ _ _ _ _ _
  }
  %% END CHORUS
}
verseC = \lyricmode {
\l His oath, his cov -- e -- nant, and blood, sup -- port me in the 'whelm -- ing flood.
\l When all a -- round my soul gives way, he then is all my hope and stay.
  %% CHORUS
  \SC {
    On Christ, the sol -- id rock, I stand; all oth -- er ground is sink -- ing sand,
    all oth -- er ground is sink -- ing sand.
  } \SO {
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    _ _ _ _ _ _ _ _
  }
  %% END CHORUS
}
verseD = \lyricmode {
\l Not earth, nor hell, my soul can move; I rest up -- on un -- chang -- ing love.
\l I trust his right -- eous char -- ac -- ter, his coun -- sel, prom -- ise, and his pow'r.
  %% CHORUS
  \SD {
    On Christ, the sol -- id rock, I stand; all oth -- er ground is sink -- ing sand,
    all oth -- er ground is sink -- ing sand.
  } \SO {
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    _ _ _ _ _ _ _ _
  }
  %% END CHORUS
}
verseE = \lyricmode {
\l When he shall come with trum -- pet sound, oh, may I then in him be found,
\l dressed in his right -- eous -- ness a -- lone, fault -- less to stand be -- fore the throne.
  %% CHORUS
  \SE {
    On Christ, the sol -- id rock, I stand; all oth -- er ground is sink -- ing sand,
    all oth -- er ground is sink -- ing sand.
  } \SO {
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    _ _ _ _ _ _ _ _
  }
  %% END CHORUS
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/5verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-5verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
