\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Frederick C. Maker," \italic "Congregational Church Hymnal," "1887" }
poet = \smallText \markup { "Text: John Greenleaf Whittier," \italic "The Atlantic Monthly," "1872" }
meter = \smallText "REST (WHITTIER) 86. 886"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
postscore_text = \postscoreText "*Alternate phrase: Dear Lord, thou life of humankind"

verseCount = 5
tags = "english christian 4part"
dateAdded = "2026-07-26"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Dear Lord and Father of mankind"
hymnKey = \key d \major
hymnTime = \time 4/4
quarternoteTempo = 90
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  \partial 4 fs'4 | fs'4. fs'8 es'4 fs'4 | a'4 a'4 gs'4 g'4 | fs'4. d'8 d'4 e'4 | e'2. fs'4 | fs'4. g'8 a'4 d''4 | d''4. cs''8 b'4 b'4 | b'4. a'8 g'4 gs'4 | a'4 g'4 fs'4 a'4 | d'4. d'8 d'4 e'4 | fs'2.
\bar "|."
}
alto = { \globalParts
  \partial 4 d'4 | d'4. d'8 d'4 d'4 | d'4 d'4 d'4 e'4 | d'4. d'8 d'4 d'4 | cs'2. d'4 | d'4. cs'8 d'4 d'4 | e'4. e'8 d'4 d'4 | d'4. ds'8 e'4 e'4 | e'4 e'4 d'4 d'4 | d'4. d'8 d'4 cs'4 | d'2.
}
tenor = { \globalParts
  \partial 4 a4 | a4. a8 gs4 a4 | a4 a4 b4 a4 | a4. fs8 fs4 gs4 | a2. a4 | a4. a8 a4 a4 | as4. as8 b4 b4 | b4. b8 b4 b4 | a4 a4 a4 c'4 | c'4. b8 b4 bf4 | a2.
}
bass = { \globalParts
  \partial 4 d4 | d4. d8 d4 d4 | fs4 fs4 e4 cs4 | d4. d8 b,4 b,4 | a,2. d4 | d4. e8 fs4 fs4 | fs4. fs8 g4 g4 | g4. fs8 e4 d4 | cs4 cs4 d4 fs4 | g4. g8 g4 g4 | d2.
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l "*Dear" Lord and Fa -- ther of man -- kind, for -- give our fool -- ish ways. Re -- clothe us in our right -- ful mind, in pur -- er lives thy ser -- vice find, in deep -- er rev -- 'rence praise. 
}
verseB = \lyricmode {
In sim -- ple trust like theirs who heard, be -- side the Syr -- ian sea, the gra -- ciaus call -- ing of the Lord, let us, like them, with -- out a word rise up and fol -- low thee. 
}
verseC = \lyricmode {
O Sab -- bath rest by Gal -- i -- lee! O calm of hills a -- bove, where Je -- sus knelt to share with thee the si -- lence of e -- ter -- ni -- ty, in -- ter -- pret -- ed by love; 
}
verseD = \lyricmode {
drop thy still dews of qui -- et -- ness, till all our striv -- ings cease. Take from our souls the strain and stress, and let our or -- dered lives con -- fess the beau -- ty of thy peace. 
}
verseE = \lyricmode {
Breathe through the heats of our de -- sire thy cool -- ness and thy balm. Let sense be dumb, let flesh re -- tire, speak through the earth -- quake, wind, and fire, O still small voice of calm! 
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/5verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-5verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
