\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Composer," \italic "Book," "year" }
poet = \smallText \markup { "Text: Author," \italic "Book," "year" }
meter = \smallText "TUNE NAME meter"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 1
tags = "english christian 4part"
dateAdded = "2026-07-25"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "When Jesus wept"
hymnKey = \key g \major
hymnTime = \time 3/2
quarternoteTempo = 200
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  \time 3/2 \partial 2 e'2 | b'1 a'2 | b'4.( c''8 d''2) g'2 | b'4.( a'8 g'2) fs'2 | e'1 e'2 | e'1 d'2 | g'2( fs'2) e'2 | e'1 b2 | e'1 | b'2 | e''2( b'2) d''2 | g'2( a'2) b'2 | b'1 b'2 | b'1 g'2 | b'4.( a'8 g'2) fs'2 | g'2( c''2) b'2 | g'4.( fs'8 e'2) d'2 | e'1
\bar "|."
}
%% This is a round, not a four-part setting: all four voices sing the
%% soprano line, entering a measure apart. The lower parts stay empty, but
%% the variables have to exist - lib/traditional-book.ily references them.
alto = {}
tenor = {}
bass = {}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l When Je -- sus "wept," the fall -- ing tear
\l in mer -- cy flowed be -- yond all "bound."
\l When Je -- sus "groaned," a trem -- bling fear
\l seized all the guilt -- y world a -- "round."
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/1verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-1verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
