\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: William Billings," \italic "The New-England Psalm-Singer," "1770" }
poet = \smallText \markup { "Text: William Billings," \italic "The New-England Psalm-Singer," "1770" }
meter = \smallText "WHEN JESUS WEPT 8.8.8.8"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
postscore_text = \postscoreText "A four-voice round: each voice enters in turn, one measure apart."

verseCount = 1
tags = "english christian 1part round"
dateAdded = "2026-07-25"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "When Jesus wept"
hymnKey = \key g \major
hymnTime = \time 3/2
quarternoteTempo = 200
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  %% One system per phrase - this song is 16 measures of four equal
  %% phrases, so that works out to a break every 4 measures. Each break
  %% cuts a measure in half so the next phrase opens on its upbeat, hence
  %% the repeated \partial 2.
  %%
  %% The 1/2/3/4 marks are the canon entries: voice 2 starts when voice 1
  %% reaches the second system, and so on.
  \time 3/2 \partial 2 e'2^\markup { \bold "1" } | b'1 a'2 | b'4.( c''8 d''2) g'2 | b'4.( a'8 g'2) fs'2 | e'1
  \break
  \partial 2 e'2^\markup { \bold "2" } | e'1 d'2 | g'2( fs'2) e'2 | e'1 b2 | e'1
  \break
  \partial 2 b'2^\markup { \bold "3" } | e''2( b'2) d''2 | g'2( a'2) b'2 | b'1 b'2 | b'1
  \break
  \partial 2 g'2^\markup { \bold "4" } | b'4.( a'8 g'2) fs'2 | g'2( c''2) b'2 | g'4.( fs'8 e'2) d'2 | e'1
\bar "|."
}
%% This is a round, not a four-part setting: all four voices sing the
%% soprano line, entering a measure apart. The lower parts stay empty, but
%% the variables have to exist - lib/traditional-book.ily references them.
alto = {}
tenor = {}
bass = {}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l When Je -- sus "wept," the fall -- ing tear
\l in mer -- cy flowed be -- yond all "bound."
\l When Je -- sus "groaned," a trem -- bling fear
\l seized all the guilt -- y world a -- "round."
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/1verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-1verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
