\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \twoLineSmallText \markup { "Music: William F. Sherwin, 1877," } \markup { \italic "The Calvary Selection of Spiritual Songs," "1878" }
poet = \smallText \markup { "Text: Mary A. Lathbury," \italic "Chautauqua Carols," "1877" }
meter = \smallText "BREAD OF LIFE 64.64D"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 2
tags = "english christian 4part"
dateAdded = "2026-07-26"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Break thou the bread of life"
hymnKey = \key ef \major
hymnTime = \time 2/2
quarternoteTempo = 130
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  g'2 ef'4 g'4 | bf'4 c''4 bf'2 | g'2 ef'4 g'4 | f'1 | g'2 ef'4 g'4 | bf'4 c''4 bf'4 c''4 | d''2 c''2 | bf'1 | f'2 g'4 af'4 | c''4 bf'4 g'2 | bf'2 c''4 c''4 | d''1 | ef''2 bf'4 g'4 | f'4 af'4 c''4 af'4 | f'2 bf'2 | ef'1
\bar "|."
}
alto = { \globalParts
  ef'2 bf4 ef'4 | g'4 af'4 g'2 | ef'2 bf4 ef'4 | d'1 | ef'2 bf4 ef'4 | g'4 af'4 g'4 g'4 | f'2 ef'2 | d'1 | d'2 ef'4 f'4 | af'4 g'4 ef'2 | f'2 f'4 f'4 | f'2( af'2) | g'2 g'4 ef'4 | ef'4 ef'4 ef'4 ef'4 | ef'2 d'2 | bf1
}
tenor = { \globalParts
  bf2 g4 bf4 | ef'4 ef'4 ef'2 | bf2 g4 bf4 | bf1 | bf2 g4 bf4 | ef'4 ef'4 ef'4 bf4 | bf2 a2 | bf1 | bf2 bf4 d'4 | ef'4 ef'4 bf2 | bf2 a4 a4 | bf1 | bf2 ef'4 bf4 | c'4 c'4 c'4 c'4 | bf2 af2 | g1
}
bass = { \globalParts
  ef2 ef4 ef4 | ef4 ef4 ef2 | ef2 ef4 ef4 | bf,1 | ef2 ef4 ef4 | ef4 ef4 ef4 ef4 | f2 f2 | bf,1 | bf,2 bf,4 bf,4 | ef4 ef4 ef2 | d2 c4 c4 | bf,1 | ef2 ef4 ef4 | af,4 af,4 af,4 af,4 | bf,2 bf,2 | ef1
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l Break thou the bread of life, dear Lord, to me, as thou didst break the loaves be -- side the sea. Be -- yond the sa -- cred page I seek thee, Lord; my spir -- it pants for thee, O liv -- ing Word. 
}
verseB = \lyricmode {
Bless thou the truth, dear Lord, now un -- to me, as thou didst bless the bread by Gal -- i -- lee. Then shall all bond -- age cease, all fet -- ters fall, and I shall find my peace, my All -- in -- all. 
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/2verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-2verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
