\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Robert Lowry, 1874," \italic "Brightest and Best," "1875" }
poet = \smallText \markup { "Text: Robert Lowry, 1874," \italic "Brightest and Best," "1875" }
meter = \smallText "CHRIST AROSE 11 10 with refrain"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 3
tags = "english christian 4part"
dateAdded = "2026-07-31"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Low in the grave he lay"
hymnKey = \key c \major
hymnTime = \time 4/4
quarternoteTempo = 110
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  g'2 g'4 a'4 | a'4 g'4 g'2 | g'2 f'4 a'4 | a'2 g'2 | \break
  a'2 b'4 c''4 | c''4 g'4 g'2 | a'2 g'4 fs'4 | g'1 \bar "||" | c'4 c'8. c'16 e'4 g'8. g'16 | \break
  c''2. c''8. d''16 | e''4 c''4 d''8. c''16 b'8. a'16 | g'2. b'8. c''16 | d''4 d''4 d''8. c''16 d''8. e''16 | \break
  c''4 a'4 g'4 g'8. g'16 | a'4 a'4 a'8. d''16 d''8. c''16 |
  %% m16 is split so the "He a-" pickup opens the last system, as the page
  %% prints it; hides the barline the split would otherwise draw.
  b'4 c''4 d''4 \break
  g'8. g'16 | e''2. d''8. c''16 | f''2. e''8. d''16 | c''4 g'4 e''4 d''4 | c''1
\bar "|."
}
alto = { \globalParts
  e'2 e'4 f'4 | f'4 e'4 e'2 | d'2 d'4 f'4 | f'2 e'2 | f'2 g'4 a'4 | g'4 e'4 e'2 | e'2 d'4 c'4 | b1 | c'4 c'8. c'16 e'4 g'8. g'16 | e'2. e'8. f'16 | g'4 g'4 a'8. a'16 g'8. f'16 | e'2. d'8. e'16 | f'4 f'4 f'8. e'16 f'8. g'16 | e'4 f'4 e'4 e'8. e'16 | f'4 f'4 f'8. f'16 f'8. a'16 | g'8 f'8 e'4 g'4 g'8. g'16 | g'2. f'8. e'16 | a'2. g'8. f'16 | e'4 e'4 g'4 f'4 | e'1
}
tenor = { \globalParts
  %% m16-18: the converter put the "He a-rose!" echo a beat early. The page
  %% enters it on beat 2, in unison with the bass.
  c'2 c'4 c'4 | c'4 c'4 c'2 | b2 b4 b4 | c'2 c'2 | c'2 c'4 c'4 | c'4 c'4 c'2 | c'2 b4 a4 | g1 | c4 c8. c16 e4 g8. g16 | g4 g8. g16 g4 c'8. c'16 | c'4 c'4 c'8. c'16 c'8. c'16 | c'4 c'8. c'16 c'4 g8. g16 | g4 g4 g8. g16 g8. g16 | c'4 c'4 c'4 c'8. c'16 | c'4 c'4 c'8. a16 a8. d'16 | d'4 c'4 b4 r4 | r4 c'8. c'16 c'4 r4 | r4 c'8. c'16 c'4 c'8. a16 | g4 c'4 c'4 b4 | c'1
}
bass = { \globalParts
  c2 c4 c4 | c4 c4 c2 | g,2 g,4 g,4 | c2 c2 | f2 f4 f4 | e4 c4 c2 | a,2 d4 d4 | g,1 | c4 c8. c16 e4 g8. g16 | c4 c8. c16 c4 c8. c16 | c4 e4 f8. f16 f8. f16 | c4 c8. c16 c4 g8. g16 | g4 g4 g8. g16 g8. g16 | a4 f4 c4 c8. c16 | f4 f4 d8. d16 d8. d16 | g4 a4 g4 r4 | r4 c'8. c'16 c'4 r4 | r4 f8. f16 f4 f8. f16 | g4 g4 g4 g4 | c1
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

%% The page sets a second text line under the bass staff in the refrain:
%% the tenor/bass echo "he a-rose!" under the soprano's held notes in
%% m10, m12, m17 and m18. Skips carry it past every other note.
tenorRefrain = \lyricmode {
  _ _ _
  _ _ _
  _ _ _
  _ _
  _ _ _
  _ _ _
  _ _ _
  _
  _ _ _ _ _ _
  _ he a -- rose, _ _
  _ _ _ _ _ _
  _ He a -- rose! _ _
  _ _ _ _ _ _
  _ _ _ _ _
  _ _ _ _ _ _
  _ _ _
  He a -- rose!
  He a -- rose! _ _
  _ _ _ _
  _
}

verseA = \lyricmode {
\l Low in the grave he lay, Je -- sus, my Sav -- ior!
\l Wait -- ing the com -- ing day, Je -- sus, my Lord!
  %% CHORUS
\l Up from the grave he a -- rose,
\l with a might -- y tri -- umph o'er his foes!
\l He a -- rose a vic -- tor from the dark do -- main,
\l and he lives for -- ev -- er with his saints to reign!
\l He a -- rose! He a -- rose!
\l Al -- le -- lu -- ia! Christ a -- rose!
  %% END CHORUS
}
verseB = \lyricmode {
\l Vain -- ly they watch his bed, Je -- sus, my Sav -- ior!
\l Vain -- ly they seal the dead, Je -- sus, my Lord!
  %% CHORUS
  \SB {
    Up from the grave he a -- rose,
    with a might -- y tri -- umph o'er his foes!
    He a -- rose a vic -- tor from the dark do -- main,
    and he lives for -- ev -- er with his saints to reign!
    He a -- rose! He a -- rose!
    Al -- le -- lu -- ia! Christ a -- rose!
  } \SO {
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  }
  %% END CHORUS
}
verseC = \lyricmode {
\l Death can -- not keep its prey, Je -- sus, my Sav -- ior!
\l He tore the bars a -- way, Je -- sus, my Lord!
  %% CHORUS
  \SC {
    Up from the grave he a -- rose,
    with a might -- y tri -- umph o'er his foes!
    He a -- rose a vic -- tor from the dark do -- main,
    and he lives for -- ev -- er with his saints to reign!
    He a -- rose! He a -- rose!
    Al -- le -- lu -- ia! Christ a -- rose!
  } \SO {
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  }
  %% END CHORUS
}



% Set up music-aligned verses. Inlined rather than \include "3verse.ily"
% so the tenor echo line can be attached; otherwise identical.
all_verses = <<
  \new NullVoice = "soprano" {\removeWithTag #'midionly \soprano}
  \new NullVoice = "tenor" {\removeWithTag #'midionly \tenor}
  \tag #'verseA { \new Lyrics  \lyricsto soprano  { \globalLyrics "1" "" \verseA } }
  \tag #'verseB { \new Lyrics  \lyricsto soprano  { \globalLyrics "2" "" \verseB } }
  \tag #'verseC { \new Lyrics  \lyricsto soprano  { \globalLyrics "3" "" \verseC } }
  \new Lyrics  \lyricsto tenor  { \globalLyrics "" "" \tenorRefrain }
>>

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-3verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
