\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Asa Hull," \italic "Sabbath School Gems," "1864, alt." }
poet = \smallText \markup { "Text: R. Torry, Jr.," \italic "Sabbath School Gems," "1864" }
meter = \smallText "THE BEAUTIFUL RIVER 11 7. 11 7 with refrain"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 4
tags = "english christian 4part"
dateAdded = "2026-07-28"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Oh, have you not heard"
hymnKey = \key af \major
hymnTime = \time 3/4
quarternoteTempo = 145
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

%% Five systems, as the page prints them. The verse is m1-16 and the refrain
%% m17-33, with the standalone ef'4 of m17 as the refrain's pickup.
%% \bar "||" after m16 closes the verse before the refrain (source m16 barline
%% light-light, dropped by the converter).
%%
%% The page prints "Refrain" over m17 (source m17 <words>Refrain</words>, also
%% dropped), but no song in this repo marks one on the staff - the convention
%% here is to say "with refrain" in the meter string, as my-hope-is-built-on-
%% nothing-less and blessed-assurance do, and let the lyrics carry it. The tune
%% line on the page says the same: "THE BEAUTIFUL RIVER 11 7. 11 7 with refrain".
%%
%% The source's backward repeat at m33 is a MuseScore artifact for "sing the
%% next stanza"; this repo expands stanzas as verseA-D, so it is not a volta
%% and is deliberately not reproduced.
soprano = { \globalParts
  \partial 4 ef'4 | af'4. af'8 af'4 | af'4 g'4 af'4 | bf'4. af'8 g'4 | af'2 af'4 | c''4. af'8 af'4 | af'4( g'4) af'4 | bf'2.~ | bf'2 \break ef'4 | c''4. c''8 c''4 | af'4. af'8 af'4 | bf'4. af'8 bf'4 | c''2 df''4 | c''4. bf'8 af'4 | bf'4( af'4) g'4 | af'2.~ | af'2 \bar "||" \break ef'4 | af'2 af'4 | af'4 g'4 af'4 | bf'2.~ | bf'2 bf'4 | bf'2 bf'4 | bf'4 af'4 bf'4 | c''2.~ | c''2 \break af'4 | c''4. c''8 c''4 | df''2 c''4 | bf'4. af'8 bf'4 | c''2 df''4 | c''2 af'4 | bf'4. af'8 g'4 | af'2.~ | af'2
\bar "|."
}
alto = { \globalParts
 \partial 4 ef'4 | ef'4. ef'8 ef'4 | ef'4 ef'4 ef'4 | f'4. ef'8 ef'4 | ef'2 ef'4 | af'4. ef'8 ef'4 | ef'4( ef'4) ef'4 | g'2.~ | g'2 ef'4 | ef'4. ef'8 ef'4 | ef'4. ef'8 ef'4 | g'4. f'8 g'4 | af'2 af'4 | af'4. g'8 f'4 | f'4( ef'4) ef'4 | ef'2.~ | ef'2 ef'4 | ef'2 ef'4 | ef'4 ef'4 ef'4 | g'2.~ | g'2 g'4 | g'2 g'4 | g'4 ef'4 g'4 | af'2.~ | af'2 af'4 | af'4. af'8 af'4 | af'2 af'4 | g'4. ef'8 g'4 | af'2 f'4 | ef'2 ef'4 | f'4. ef'8 ef'4 | ef'2.~ | ef'2
}
tenor = { \globalParts
 \partial 4 ef4 | c'4. c'8 c'4 | c'4 df'4 c'4 | df'4. c'8 bf4 | c'2 c'4 | ef'4. c'8 c'4 | c'4( df'4) c'4 | ef'2.~ | ef'2 ef4 | af4. af8 af4 | c'4. c'8 c'4 | ef'4. c'8 ef'4 | ef'2 f'4 | ef'4. df'8 c'4 | df'4( c'4) bf4 | c'2.~ | c'2 ef4 | c'2 c'4 | c'4 df'4 c'4 | ef'2.~ | ef'2 ef'4 | ef'2 ef'4 | ef'4 c'4 ef'4 | ef'2.~ | ef'2 c'4 | ef'4. ef'8 ef'4 | f'2 ef'4 | df'4. c'8 ef'4 | ef'2 af4 | af2 c'4 | df'4. c'8 bf4 | c'2.~ | c'2
}
bass = { \globalParts
 \partial 4 ef4 | af,4. af,8 af,4 | af,4 bf,4 af,4 | df4. ef8 ef4 | af,2 af4 | af4. af8 af4 | af4( bf4) af4 | ef2.~ | ef2 ef4 | af,4. af,8 af,4 | af4. af8 af4 | ef4. f8 ef4 | af2 df4 | ef4. ef8 f4 | df4( ef4) ef4 | af,2.~ | af,2 ef4 | af2 af4 | af4 bf4 af4 | ef2.~ | ef2 ef4 | ef2 ef4 | ef4 ef4 ef4 | af2.~ | af2 af4 | af4. af8 af4 | af2 af4 | ef4. ef8 ef4 | af2 df4 | ef2 ef4 | df4. ef8 ef4 | af,2.~ | af,2
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l Oh, have you not heard of that beau -- ti -- ful stream that
\l flows through the prom -- ised land?
\l Its wa -- ters gleam bright in the heav -- en -- ly light, and
\l rip -- ple o'er gold -- en sand.
  %% REFRAIN
  %% 4verse.ily passes "1" as the laterLabel, so the stanza number repeats
  %% at the start of every system - including the refrain, which belongs to
  %% no one stanza. Clear it here so the refrain systems carry no number, as
  %% the page prints them. \SO keeps this out of the slides.
  \SO { \set shortVocalName = "" }
\l O seek that beau -- ti -- ful stream, O seek that beau -- ti -- ful stream.
\l Its wa -- ters, so free, are flow -- ing for thee,
\l O seek that beau -- ti -- ful stream.
  %% END REFRAIN
}
verseB = \lyricmode {
\l Its foun -- tains are deep and its wa -- ters are pure, and
\l sweet to the wea -- ry soul.
\l It flows from the throne of Je -- ho -- vah a -- lone! O
\l come where its bright waves roll.
  %% REFRAIN
  \SB {
    O seek that beau -- ti -- ful stream, O seek that beau -- ti -- ful stream.
    Its wa -- ters, so free, are flow -- ing for thee,
    O seek that beau -- ti -- ful stream.
  } \SO {
    _ _ _ _ _ _ _ _ _ _ _ _ _ _
    _ _ _ _ _ _ _ _ _ _
    _ _ _ _ _ _ _
  }
  %% END REFRAIN
}
verseC = \lyricmode {
\l This beau -- ti -- ful stream is the riv -- er of life! It
\l flows for all na -- tions free!
\l A balm for each wound in its wa -- ter is found; O
\l sin -- ner, it flows for thee!
  %% REFRAIN
  \SC {
    O seek that beau -- ti -- ful stream, O seek that beau -- ti -- ful stream.
    Its wa -- ters, so free, are flow -- ing for thee,
    O seek that beau -- ti -- ful stream.
  } \SO {
    _ _ _ _ _ _ _ _ _ _ _ _ _ _
    _ _ _ _ _ _ _ _ _ _
    _ _ _ _ _ _ _
  }
  %% END REFRAIN
}
verseD = \lyricmode {
\l Oh, will you not drink of this beau -- ti -- ful stream, and
\l dwell on its peace -- ful shore?
\l The Spir -- it says: Come, all ye wea -- ry ones, home, and
\l wan -- der in sin no more.
  %% REFRAIN
  \SD {
    O seek that beau -- ti -- ful stream, O seek that beau -- ti -- ful stream.
    Its wa -- ters, so free, are flow -- ing for thee,
    O seek that beau -- ti -- ful stream.
  } \SO {
    _ _ _ _ _ _ _ _ _ _ _ _ _ _
    _ _ _ _ _ _ _ _ _ _
    _ _ _ _ _ _ _
  }
  %% END REFRAIN
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/4verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
clairStaffZoom = #.85
tradStaffZoom = #.85
shapeStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-4verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
