\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Composer," \italic "Book," "year" }
poet = \smallText \markup { "Text: Author," \italic "Book," "year" }
meter = \smallText "TUNE NAME meter"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 1
tags = "english christian 4part"
dateAdded = "2026-07-25"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Dona nobis pacem"
hymnKey = \key f \major
hymnTime = \time 3/4
quarternoteTempo = 100
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  \time 3/4 f'8 c'8 a'2 | g'8 c'8 bf'2 | a'4( g'4) f'4 | f'4 e'2 | d''4( c''8 bf'8) a'8 g'8 | c''4.( bf'8) a'4 | a'8( g'8 f'4 e'4) | f'2. | c''2. | c''2. | c''4( bf'4) a'4 | a'4 g'2 | d''4 d''2 | c''4 c''2 | c''8( bf'8 a'4 g'4) | f'2. | f'2. | e'2. | f'4.( g'8) a'8 bf'8 | c''4 c'2 | bf'4 bf'2 | a'4 a'2 | e'8( g'8 c''4 c'4) | f'2.
\bar "|."
}
alto = { \globalParts
  \time 3/4
}
tenor = { \globalParts
  \time 3/4
}
bass = { \globalParts
  \time 3/4
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l Do -- na no -- bis pa -- "cem,*" pa -- "cem." Do -- na no -- bis pa -- "cem." Do -- na no -- bis pa -- "cem." Do -- na no -- bis pa -- "cem." Do -- na no -- bis pa -- "cem." Do -- na no -- bis pa -- "cem." 
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/1verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-1verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
