\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Clara H. Scott," \italic "Best Hymns, No. 2," "1895" }
poet = \smallText \markup { "Text: Clara H. Scott," \italic "Best Hymns, No. 2," "1895" }
meter = \smallText "OPEN MY EYES 88. 98. 88. 84"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 4
tags = "english christian 4part"
dateAdded = "2026-07-30"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Open my eyes, that I may see"
hymnKey = \key af \major
hymnTime = \time 6/8
hymnBaseMoment = \set Timing.baseMoment = #(ly:make-moment 1/8)
hymnBeatStructure = \set Timing.beatStructure = 3,3
quarternoteTempo = 100
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  \pa af'8 g'8 f'8 \pt ef'4 f'8 | f'4 ef'8 ef'4. | bf'8 g'8 f'8 ef'4 g'8 | f'4 ef'8 ef'4. \break
  \pa e'8 d'8 e'8 \pt f'4 f'8 | g'8 f'8 g'8 af'4. | f'8 g'8 af'8 bf'4 g'8 | g'4 f'8 ef'4. \break
  \pa af'8 g'8 f'8 \pt ef'4 f'8 | f'4 ef'8 ef'4. | bf'8 g'8 f'8 ef'4 g'8 | f'4 ef'8 ef'4. \break
  c''8 bf'8 af'8 af'4 af'8 | bf'4 af'8 f'4. | ef'4. bf'4 af'8 | af'4.~ af'4.
\bar "|."
}
alto = { \globalParts
  ef'8 ef'8 ef'8 ef'4 ef'8 | df'4 df'8 df'4. | df'8 df'8 df'8 df'4 df'8 | c'4 c'8 c'4. | c'8 c'8 c'8 c'4 c'8 | c'8 c'8 e'8 f'4. | d'8 d'8 d'8 d'4 d'8 | d'4 d'8 ef'4. | ef'8 ef'8 ef'8 ef'4 ef'8 | df'4 df'8 df'4. | df'8 df'8 df'8 df'4 df'8 | c'4 c'8 c'4. | ef'8 ef'8 ef'8 gf'4 gf'8 | f'4 f'8 df'4. | df'4. df'4 c'8 | c'4.~ c'4.
}
tenor = { \globalParts
  c'8 c'8 c'8 c'4 af8 | g4 g8 g4. | g8 bf8 af8 g4 bf8 | af4 af8 af4. | bf8 bf8 bf8 af4 af8 | bf8 af8 bf8 af4. | af8 g8 f8 f4 bf8 | bf4 af8 g4. | c'8 c'8 c'8 c'4 af8 | g4 g8 g4. | g8 bf8 af8 g4 bf8 | af4 af8 af4. | af8 g8 af8 af4 af8 | af4 af8 af4. | g4. g4 af8 | af4.~ af4.
}
bass = { \globalParts
  af,8 af,8 af,8 af,4 af,8 | bf,4 bf,8 bf,4. | ef8 ef8 ef8 ef4 ef8 | af4 af8 af4. | g8 g8 g8 f4 f8 | e8 f8 c8 f4. | bf,8 bf,8 bf,8 bf,4 bf,8 | bf,4 bf,8 ef4. | af,8 af,8 af,8 af,4 af,8 | bf,4 bf,8 bf,4. | ef8 ef8 ef8 ef4 ef8 | af4 af8 af4. | af,8 bf,8 c8 c4 c8 | df4 df8 df4. | ef4. ef4 af,8 | af,4.~ af,4.
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
  \l O -- pen my eyes, that I may see glimps -- es of truth thou hast for me.
  \l Place in my hands the won -- der -- ful key that shall un -- clasp, and set me free.
  \l Si -- lent -- ly now I wait for thee, read -- y, my God, thy will to see.
  \l O -- pen my eyes, il -- lu -- mine me, Spir -- it di -- vine!
}
verseB = \lyricmode {
  O -- pen my ears, that I may hear voic -- es of truth thou send -- est clear,
  and while the wave notes fall on my ear, ev -- 'ry -- thing false will dis -- ap -- pear.
  Si -- lent -- ly now I wait for thee, read -- y, my God, thy will to see.
  O -- pen my ears, il -- lu -- mine me, Spir -- it di -- vine!
}
verseC = \lyricmode {
  O -- pen my mouth, and let me bear glad -- ly the warm truth ev -- 'ry -- where.
  O -- pen my heart, and let me pre -- pare love with thy chil -- dren thus to share.
  Si -- lent -- ly now I wait for thee, read -- y, my God, thy will to see.
  O -- pen my heart, il -- lu -- mine me, Spir -- it di -- vine!
}
verseD = \lyricmode {
  O -- pen my mind, that I may read more of thy love in word and deed.
  What shall I fear while yet thou dost lead? On -- ly for light from thee I plead.
  Si -- lent -- ly now I wait for thee, read -- y, my God, thy will to see.
  O -- pen my mind, il -- lu -- mine me, Spir -- it di -- vine!
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/4verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-4verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
