\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \twoLineSmallText \markup { "Music: African-American spiritual," } \markup { \italic "Folk Songs of the American Negro," "1907" }
poet = \twoLineSmallText \markup { "Text: African-American spiritual," } \markup { \italic "Folk Songs of the American Negro," "1907" }
meter = \smallText "LORD, I WANT TO BE irregular"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 4
tags = "english christian 4part"
dateAdded = "2026-08-03"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Lord, I want to be a Christian"
hymnKey = \key ef \major
hymnTime = \time 4/4
quarternoteTempo = 90
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  \partial 2 ef'4 ef'4 | g'4. g'8 bf'4 g'4 | f'4 ef'4 ef'4 ef'4 | g'2 bf'4 c''4 | bf'4( g'4) 
    \break \partial 2 ef'4 ef'4 | g'4. g'8 bf'4 g'4 | f'4 ef'4 c'4 ef'4 | ef'1~ | ef'2
    \break \partial 2 ef''4 ef''4 | c''1( | ef''2) ef''4 c''4 | bf'1( | c''2) 
    \break \partial 2 ef'4 ef'4 | g'4. g'8 bf'4 g'4 | f'4 ef'4 c'4 ef'4 | ef'1~ | ef'2
\bar "|."
}
alto = { \globalParts
  \partial 2 ef'4 ef'4 | g'4. g'8 bf'4 g'4 | f'4 ef'4 bf4 bf4 | ef'2 ef'4 ef'4 | ef'2 bf4 bf4 | ef'4. ef'8 g'4 ef'4 | d'4 c'4 c'4 c'4 | bf1~ | bf2 ef'4 g'4 | af'1 | af'2 ef'4 af'4 | g'1 | g'2 bf4 bf4 | ef'4. ef'8 g'4 ef'4 | d'4 c'4 c'4 c'4 | bf1~ | bf2
}
tenor = { \globalParts
  \partial 2 ef4 ef4 | g4. g8 bf4 g4 | f4 ef4 g4 g4 | bf2 g4 af4 | g4 bf4 g4 g4 | bf4. bf8 ef'4 bf4 | bf4 g4 af4 f4 | g1~ | g2 r2 | r2 ef'4 ef'4 | c'2 r2 | r2 ef'4 ef'4 | ef'2 g4 g4 | bf4. bf8 ef'4 bf4 | af4 g4 af4 f4 | g1~ | g2
}
bass = { \globalParts
  \partial 2 ef4 ef4 | g4. g8 bf4 g4 | f4 ef4 ef4 ef4 | ef2 ef4 af,4 | ef2 ef4 ef4 | ef4. ef8 ef4 ef4 | bf,4 c4 af,4 af,4 | ef1~ | ef2 r2 | r2 af4 af4 | af2 r2 | r2 ef4 ef4 | c2 ef4 ef4 | ef4. ef8 ef4 ef4 | bf,4 c4 af,4 af,4 | ef1~ | ef2
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l Lord, I want to be a Chris -- tian in my heart, in my heart. Lord, I want to be a Chris -- tian in my heart. \l In my heart, in my heart, \l Lord, I want to be a Chris -- tian in my heart.
}
verseB = \lyricmode {
Lord, I want to be more lov -- ing...
}
verseC = \lyricmode {
Lord, I want to be more ho -- ly...
}
verseD = \lyricmode {
Lord, I want to be like Je -- sus...
}

%% Bass/tenor echo an "In my heart," a beat behind soprano/alto in the
%% "In my heart, in my heart," refrain (voice 5 in the source XML). The
%% hymnal page prints only one lyric line, but the parts genuinely sing
%% this call-and-response when performed, so it gets its own line here.
bottomA = \lyricmode {
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
In my heart, In my heart, _ _ _ _ _ _ _ _ _ _ _ _
}

all_verses = <<
  \new NullVoice = "soprano" {\removeWithTag #'midionly \soprano}
  \tag #'verseA { \new Lyrics  \lyricsto soprano  { \globalLyrics "1" "" \verseA } }
  \tag #'verseB { \new Lyrics  \lyricsto soprano  { \globalLyrics "2" "" \verseB } }
  \tag #'verseC { \new Lyrics  \lyricsto soprano  { \globalLyrics "3" "" \verseC } }
  \tag #'verseD { \new Lyrics  \lyricsto soprano  { \globalLyrics "4" "" \verseD } }
>>

bottom_verses = <<
  \new NullVoice = "bass" {\removeWithTag #'midionly \bass}
  \new Lyrics \lyricsto bass { \globalLyrics "" "" \bottomA }
>>

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-4verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
