\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: William B. Bradbury," \italic "The Golden Shower," "1862" }
poet = \smallText "Text: Anna B. Warner, 1859"
meter = \smallText "JESUS LOVES ME 77. 77 with refrain"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 1
tags = "english christian 4part"
dateAdded = "2026-07-27"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Jesus loves me"
hymnKey = \key ef \major
hymnTime = \time 2/4
quarternoteTempo = 60
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

%% Four systems, as the page prints them: m1-4, m5-8, m9-12, m13-16.
%%
%% \bar "||" after m8 closes the verse before the refrain (source m8
%% BarLine subtype=double). The page also prints "Refrain" over m9, but
%% no song in this repo marks one on the staff - the convention here is
%% to say "with refrain" in the meter string, as blessed-assurance does,
%% and let the lyrics carry it. The tune line on the page says the same.
%%
%% The fermata in m14 is on "me;" - a hold before the closing phrase,
%% NOT an ending fermata. The source puts one above the treble staff and
%% one below the bass (m14 fermataAbove / fermataBelow); both were
%% dropped by the converter. It goes on soprano and bass alone, since
%% one mark per staff is what the page shows and what blessed-assurance
%% does with its marks.
soprano = { \globalParts
  bf'8 g'8 g'8 f'8 | g'8 bf'8 bf'4 | c''8 c''8 ef''8 c''8 | c''8 bf'8 bf'4 | \break
  bf'8 g'8 g'8 f'8 | g'8 bf'8 bf'4 | c''8 c''8 bf'8 ef'8 | g'8 f'8 ef'4 \bar "||" \break
  bf'4 g'8 bf'8 | c''8 ef''4. | bf'4 g'8 ef'8 | g'8 f'4. | \break
  bf'4 g'8 bf'8 | c''8 ef''4 c''8 | bf'8 ef'8 g'8.\fermata f'16 | ef'2
\bar "|."
}
alto = { \globalParts
  g'8 ef'8 ef'8 d'8 | ef'8 g'8 g'4 | af'8 af'8 c''8 af'8 | af'8 g'8 g'4 | \break
  g'8 ef'8 ef'8 d'8 | ef'8 g'8 g'4 | af'8 af'8 g'8 ef'8 | ef'8 d'8 ef'4 \bar "||" \break
  g'4 ef'8 g'8 | af'8 c''4. | g'4 g'8 ef'8 | ef'8 d'4. | \break
  g'4 ef'8 g'8 | af'8 c''4 af'8 | g'8 ef'8 ef'8. d'16 | ef'2
}
tenor = { \globalParts
  bf8 bf8 bf8 bf8 | bf8 bf8 bf4 | af8 af8 af8 af8 | af8 bf8 bf4 | \break
  bf8 bf8 bf8 bf8 | bf8 bf8 bf4 | af8 af8 bf8 g8 | bf8 af8 g4 \bar "||" \break
  bf4 bf8 ef'8 | ef'8 ef'4. | ef'4 g8 ef8 | bf8 bf4. | \break
  bf4 bf8 ef'8 | ef'8 ef'4 ef'8 | ef'8 g8 bf8. af16 | g2
}
bass = { \globalParts
  ef8 ef8 ef8 bf,8 | ef8 ef8 ef4 | af,8 af,8 af,8 c8 | ef8 ef8 ef4 | \break
  ef8 ef8 ef8 bf,8 | ef8 ef8 ef4 | af,8 c8 ef8 ef8 | bf,8 bf,8 ef4 \bar "||" \break
  ef4 ef8 ef8 | af,8 af,4. | ef4 g8 ef8 | bf,8 bf,4. | \break
  ef4 ef8 ef8 | af,8 af,4 af,8 | ef8 ef8 bf,8._\fermata bf,16 | ef2
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

%% One \l per system. The refrain begins on the third line (m9), where
%% the page prints its "Refrain" marker.
verseA = \lyricmode {
\l Je -- sus loves me! this I know, for the Bi -- ble tells me so.
\l Lit -- tle ones to him be -- long, they are weak, but he is strong.
\l Yes, Je -- sus loves me. Yes, Je -- sus loves me.
\l Yes, Je -- sus loves me; the Bi -- ble tells me so.
}

%% The page prints four translations below the score, in two columns:
%% Spanish and Hausa on the left, Korean and Navajo on the right. They
%% are laid out here the same way. The source .mscx carries them as two
%% free Text blocks, which the converter drops with the rest of its
%% StaffText handling, so they are transcribed from the source text and
%% checked against a zoom of the page.
%%
%% Each language gets its verse and then its refrain, as the page has
%% them. They are NOT underlaid: the hymnal sets them as text below the
%% staff, not under the notes, and 16 measures will not carry five
%% languages of underlay.
%%
%% Spelling follows the PAGE where it and the source disagree:
%%   - Navajo "shil" in the source is "shił" (barred l) on the page.
%%   - "Su palabra dice así." takes the period the source omits.
%% The Navajo refrain's second line really does read "ayoo'ashó'ní"
%% without the accents that lines 1 and 3 carry - that asymmetry is the
%% hymnal's own and is reproduced rather than normalized.
%%
%% See the commit message on the translations' copyright status.
extra_verses = \markup {
  \fontsize #-2.5
  \fill-line {
    \hspace #-3.0
    \column {
      \line { \bold "SPANISH" }
      \combine \null \vspace #0.3
      \column {
"Cristo me ama, me ama a mí."
"Su palabra dice así."
"Niños pueden ir a él,"
"Quien es nuestro amigo fiel."
      }
      \combine \null \vspace #0.4
      \column {
"Sí, Cristo me ama."
"Sí, Cristo me ama."
"Sí, Cristo me ama,"
"La Biblia dice así."
      }
      \combine \null \vspace #0.7
      \line { \bold "HAUSA" }
      \combine \null \vspace #0.3
      \column {
"Yesu yana kaunarmu,"
"Wannan na sakankance."
"Gaskiyarsa ta tabbata,"
"Allah ne ya shaida shi."
      }
      \combine \null \vspace #0.4
      \column {
"I, yana sonmu, i, yana sonmu,"
"I, yana sonmu, Yesu Mai Centonmu."
      }
    }
    \column {
      \line { \bold "KOREAN" }
      \combine \null \vspace #0.3
      \column {
"Yesu sarang Hasiman"
"Georukhasin marilsei"
"Wooridrn Yakana"
"Yesu gwonsei mantoda."
      }
      \combine \null \vspace #0.4
      \column {
"Nal sarang hasim"
"Nal sarang hasim"
"Nal sarang hasim"
"Seong gyongei sseoitne."
      }
      \combine \null \vspace #0.7
      \line { \bold "NAVAJO" }
      \combine \null \vspace #0.3
      \column {
"Jesus ayóó'ashó'ní,"
"Binaaltsoos yee shił halne',"
"Álchíníigi ánísht'é,"
"Doo sidziil da, Ei bidziil."
      }
      \combine \null \vspace #0.4
      \column {
"Jesus ayóó'ashó'ní,"
"Jesus ayoo'ashó'ní,"
"Jesus ayóó'ashó'ní,"
"Bizaad yee shił halne'."
      }
    }
    \hspace #-3.0
  }
}

% Set up music-aligned verses. Change to the correct number
\include "../../lib/1verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-1verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
