\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: William B. Bradbury," \italic "The Golden Shower," "1862" }
poet = \smallText "Text: Anna B. Warner, 1859"
meter = \smallText "JESUS LOVES ME 77. 77 with refrain"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 1
tags = "english christian 4part"
dateAdded = "2026-07-27"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Jesus loves me"
hymnKey = \key ef \major
hymnTime = \time 2/4
quarternoteTempo = 60
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  bf'8 g'8 g'8 f'8 | g'8 bf'8 bf'4 | c''8 c''8 ef''8 c''8 | c''8 bf'8 bf'4 | bf'8 g'8 g'8 f'8 | g'8 bf'8 bf'4 | c''8 c''8 bf'8 ef'8 | g'8 f'8 ef'4 | bf'4 g'8 bf'8 | c''8 ef''4. | bf'4 g'8 ef'8 | g'8 f'4. | bf'4 g'8 bf'8 | c''8 ef''4 c''8 | bf'8 ef'8 g'8. f'16 | ef'2
\bar "|."
}
alto = { \globalParts
  g'8 ef'8 ef'8 d'8 | ef'8 g'8 g'4 | af'8 af'8 c''8 af'8 | af'8 g'8 g'4 | g'8 ef'8 ef'8 d'8 | ef'8 g'8 g'4 | af'8 af'8 g'8 ef'8 | ef'8 d'8 ef'4 | g'4 ef'8 g'8 | af'8 c''4. | g'4 g'8 ef'8 | ef'8 d'4. | g'4 ef'8 g'8 | af'8 c''4 af'8 | g'8 ef'8 ef'8. d'16 | ef'2
}
tenor = { \globalParts
  bf8 bf8 bf8 bf8 | bf8 bf8 bf4 | af8 af8 af8 af8 | af8 bf8 bf4 | bf8 bf8 bf8 bf8 | bf8 bf8 bf4 | af8 af8 bf8 g8 | bf8 af8 g4 | bf4 bf8 ef'8 | ef'8 ef'4. | ef'4 g8 ef8 | bf8 bf4. | bf4 bf8 ef'8 | ef'8 ef'4 ef'8 | ef'8 g8 bf8. af16 | g2
}
bass = { \globalParts
  ef8 ef8 ef8 bf,8 | ef8 ef8 ef4 | af,8 af,8 af,8 c8 | ef8 ef8 ef4 | ef8 ef8 ef8 bf,8 | ef8 ef8 ef4 | af,8 c8 ef8 ef8 | bf,8 bf,8 ef4 | ef4 ef8 ef8 | af,8 af,4. | ef4 g8 ef8 | bf,8 bf,4. | ef4 ef8 ef8 | af,8 af,4 af,8 | ef8 ef8 bf,8. bf,16 | ef2
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l Je -- sus loves me! this I know, for the Bi -- ble tells me so. Lit -- tle ones to him be -- long, they are weak, but he is strong. Yes, Je -- sus loves me. Yes, Je -- sus loves me. Yes, Je -- sus loves me; the Bi -- ble tells me so. 
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/1verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-1verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
