\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Samuel S. Wesley," \italic "Selection of Psalms and Hymns," "1864" }
poet = \smallText \markup { "Text: Samuel J. Stone," \italic "Lyra Fidelium," "1866, alt." }
meter = \smallText "AURELIA 76.76D"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 5
tags = "english christian 4part"
dateAdded = "2026-07-31"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "The church's one foundation"
hymnKey = \key ef \major
hymnTime = \time 2/2
quarternoteTempo = 100
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  %% Four systems on the page, one line of text each. The phrase boundary
  %% falls INSIDE a measure, not at a barline: each line ends on a dotted
  %% half ("Lord.", "word.", "bride;") and the quarter after it is already
  %% the upbeat to the next line ("She", "From", "with"). Breaking at the
  %% barline instead drags that upbeat onto the wrong system, which is what
  %% the first render did.
  %% So each break is \bar "" \break after the dotted half - an invisible
  %% barline that gives LilyPond a legal break point mid-measure - and the
  %% next system opens \partial 4 with the upbeat. Breaks are Score-level,
  %% so soprano alone carries them and the other three voices follow.
  \partial 4 g'4 | g'4 g'4 af'4 g'4 | g'2 f'4 ef'4 | ef'4 c''4 bf'4 af'4 | g'2. \bar "" \break
  \partial 4 af'4 | bf'4 ef''4 ef''4 d''4 | d''2 c''4 bf'4 | af'4 bf'4 g'4 ef'4 | f'2. \bar "" \break
  \partial 4 f'4 | g'4 af'4 bf'4 c''4 | c''2 bf'4 ef''4 | ef''4. d''8 c''4 g'4 | af'2. \bar "" \break
  \partial 4 f'4 | g'4 g'4 af'4 g'4 | g'2 f'4 ef'4 | ef'4 f'4 ef'4 d'4 | ef'2.
\bar "|."
}
alto = { \globalParts
  \partial 4 ef'4 | ef'4 ef'4 ef'4 ef'4 | ef'2 d'4 ef'4 | c'4 ef'4 ef'4 d'4 | ef'2. d'4 | ef'4 ef'4 ef'4 f'4 | f'2 ef'4 g'4 | af'4 f'4 ef'4 ef'4 | d'2. d'4 | ef'4 d'4 ef'4 ef'4 | ef'2 ef'4 g'4 | g'4. g'8 g'4 g'4 | f'2. f'4 | ef'4 ef'4 ef'4 ef'4 | c'2 c'4 c'4 | c'4 c'4 bf4 bf4 | bf2.
}
tenor = { \globalParts
  \partial 4 bf4 | bf4 bf4 c'4 bf4 | bf2 bf4 bf4 | f4 f4 g4 bf4 | bf2. bf4 | bf4 bf4 b4 b4 | b2 c'4 d'4 | ef'4 f'4 bf4 a4 | bf2. bf4 | bf4 bf4 bf4 af4 | af2 bf4 c'4 | c'4. b8 c'4 c'4 | c'2. bf4 | bf4 bf4 c'4 bf4 | bf2 af4 af4 | af4 af4 f4 af4 | g2.
}
bass = { \globalParts
  \partial 4 ef4 | ef4 ef4 ef4 ef4 | bf,2 af,4 g,4 | af,4 af,4 bf,4 bf,4 | ef2. f4 | g4 g4 g4 g,4 | af,2 af,4 bf,4 | c4 d4 ef4 c4 | bf,2. bf,4 | ef4 f4 g4 af4 | af2 g4 c4 | g4. f8 ef4 e4 | f2. d4 | ef4 ef4 ef4 ef4 | af,2 af,4 af,4 | f,4 f,4 bf,4 bf,4 | ef2.
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

%% The page sets one text line per system, so the lyrics break the same way.
%% "chur -- ch's" looks like a converter error and is not: the page sets
%% "church's" across two notes here, and m2 has four notes needing four
%% syllables. Joining it into one word leaves the measure short and shifts
%% every following syllable. The hyphen point is the source's, not ours.
verseA = \lyricmode {
\l The chur -- ch's one foun -- da -- tion is Je -- sus Christ her Lord.
\l She is his new cre -- a -- tion by wa -- ter and the word.
\l From heav'n he came and sought her to be his ho -- ly bride;
\l with his own blood he bought her, and for her life he died.
}
verseB = \lyricmode {
\l E -- lect from ev -- 'ry na -- tion yet one o'er all the earth,
\l her char -- ter of sal -- va -- tion: one Lord, one faith, one birth.
\l One ho -- ly name she bless -- es, par -- takes one ho -- ly food,
\l and to one hope she press -- es, with ev -- 'ry grace en -- dued.
}
%% "schi -- sms" is the same case as "chur -- ch's" above: the source's own
%% split, needed to fill m6's four notes.
verseC = \lyricmode {
\l Though with a scorn -- ful won -- der the world sees her op -- pressed,
\l by schi -- sms rent a -- sun -- der, by her -- e -- sies dis -- tressed,
\l yet saints their watch are keep -- ing, their cry goes up, ''How long?''
\l And soon the night of weep -- ing shall be the morn of song.
}
verseD = \lyricmode {
\l 'Mid toil and trib -- u -- la -- tion, and tu -- mult of her war,
\l she waits the con -- sum -- ma -- tion of peace for -- ev -- er -- more,
\l till with the vi -- sion glo -- rious her long -- ing eyes are bless'd,
\l and the great church vic -- to -- rious shall be the church at rest.
}
verseE = \lyricmode {
\l Yet she on earth hath un -- ion with God the Three -- in -- One,
\l and mys -- tic sweet com -- mun -- ion with those whose rest is won.
\l Oh, hap -- py ones and ho -- ly! Lord, give us grace that we,
\l like them, the meek and low -- ly, on high may dwell with thee.
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/5verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-5verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
