\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \twoLineSmallText \markup { "Music: Richard Redhead," } \markup { \italic "Church Hymn Tunes, Ancient and Modern," "1853" }
poet = \twoLineSmallText \markup { "Text: Thomas T. Lynch," } \markup { \italic "The Rivulet: A Contribution to Sacred Song," "1855, alt." }
meter = \smallText "REDHEAD NO. 76 (GETHSEMANE) 77. 77. 77"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 5
tags = "english christian 4part"
dateAdded = "2026-08-02"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Gracious Spirit, dwell with me"
hymnKey = \key ef \major
hymnTime = \time 2/2
quarternoteTempo = 100
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

%% Three measures to a system. The meter is 77. 77. 77 - six lines of seven
%% syllables, two measures each - so the systems deliberately cut across the
%% poetry rather than following it: one line per system needs six systems,
%% and five stacked verses make that too tall for a single page.
soprano = { \globalParts
  ef'4 ef'4 f'4 g'4 | af'4. af'8 g'2 | ef'4 ef'4 f'4 g'4 \break
  | f'4 f'4 ef'2 | ef'4 g'4 bf'4 bf'4 | c''4 c''4 bf'2 \break
  | ef'4 g'4 bf'4 bf'4 | c''4 c''4 bf'2 | ef'4 ef'4 f'4 g'4 \break
  | af'4. af'8 g'2 | ef'4 f'4 g'4 f'4 | ef'4 d'4 ef'2
\bar "|."
}
alto = { \globalParts
  bf4 bf4 d'4 ef'4 | ef'4. ef'8 ef'2 | bf4 c'4 d'4 ef'4 | ef'4 d'4 bf2 | ef'4 ef'4 f'4 g'4 | ef'4 f'4 g'2 | ef'4 ef'4 f'4 d'4 | g'4 f'8 ef'8 d'2 | ef'4 ef'4 d'4 ef'4 | ef'4. ef'8 ef'2 | ef'4 d'4 ef'4 c'4 | bf4 bf4 bf2
}
tenor = { \globalParts
  g4 g4 bf4 bf4 | c'4. c'8 bf2 | g4 g4 bf4 bf4 | c'4 bf4 g2 | g4 c'4 d'4 ef'4 | c'4 d'4 ef'2 | bf4 bf4 bf4 bf4 | bf4 a4 bf2 | bf4 bf4 af4 bf4 | c'4. c'8 bf2 | bf4 af4 bf4 af4 | g4 f4 g2
}
bass = { \globalParts
  ef4 ef4 bf,4 ef4 | af,4. af,8 ef2 | ef4 c4 bf,4 ef4 | af,4 bf,4 ef2 | ef4 c4 bf,4 ef4 | af4 af4 ef2 | g4 ef4 d4 g4 | ef4 f4 bf,2 | g4 g4 f4 ef4 | af,4. af,8 ef2 | g4 f4 ef4 af,4 | bf,4 bf,4 ef2
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l Gra -- cious Spir -- it, dwell with me: I my -- self would
\l gra -- cious be, and, with words that help and heal,
\l would thy life in mine re -- veal, and, with ac -- tions
\l bold and meek, would for Christ my Sav -- ior speak.
}
verseB = \lyricmode {
\l Truth -- ful Spir -- it, dwell with me: I my -- self would
\l truth -- ful be, and, with wis -- dom kind and clear,
\l let thy life in mine ap -- pear, and, with ac -- tions
\l lov -- ing -- ly speak my Lord's sin -- cer -- i -- ty.
}
verseC = \lyricmode {
\l Si -- lent Spir -- it, dwell with me: I my -- self would
\l si -- lent be, qui -- et as the grow -- ing blade,
\l which through earth its way has made, si -- lent -- ly, like
\l morn -- ing light, put -- ting mists and chills to flight.
}
verseD = \lyricmode {
\l Might -- y Spir -- it, dwell with me: I my -- self would
\l might -- y be, might -- y so as to pre -- vail
\l where un -- aid -- ed I must fail, ev -- er, by a
\l might -- y hope, press -- ing on and bear -- ing up.
}
verseE = \lyricmode {
\l Ho -- ly Spir -- it, dwell with me: I my -- self would
\l ho -- ly be, break from sin and choose the good,
\l cher -- ish what my Sav -- ior would, and what -- ev -- er
\l I can be, give to him who gave me thee.
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/5verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-5verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
