\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \twoLineSmallText \markup { "Music:" \italic "Nederlandtsche Gedenckclanck," "1626;" } "adapt. Edward Kremser, 1877"
poet = \twoLineSmallText \markup { "Text:" \italic "Nederlandtsche Gedenckclanck," "1626;" } "tr. Theodore Baker, 1917"
meter = \smallText "KREMSER 12 11. 12 11"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 3
tags = "english christian 4part"
dateAdded = "2026-07-22"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "We gather together"
hymnKey = \key d \major
hymnTime = \time 3/4
quarternoteTempo = 115
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  \time 3/4 \partial 4 a'4 | a'4. b'8 a'4 | fs'4 g'4 a'4 | g'4. fs'8 e'4 | fs'4 d'4 \break
  \partial 4 a'4 | a'4. b'8 cs''4 | d''4. e''8 cs''4 | b'4. a'8 b'4 | a'2 \break
  \partial 4 a'4 | a'4. b'8 cs''4 | d''4 a'4 a'4 | a'4.( b'8) g'8 a'8 | fs'4 d'4 \break
  \partial 4 d'4 | g'4. a'8 b'8 g'8 | a'4.( g'8) fs'8\( fs'8\) | g'4 e'4. d'8 | d'2
\bar "|."
}
alto = { \globalParts
  \time 3/4 \partial 4 d'4 | d'4. d'8 d'4 | d'4 d'4 d'4 | d'4. d'8 cs'4 | d'4 d'4 fs'4 | e'4. e'8 e'4 | fs'4 e'4 e'4 | fs'4. fs'8 gs'4 | e'2 e'4 | e'4. e'8 e'4 | d'4 d'4 d'4 | d'2 cs'8 cs'8 | d'4 d'4 d'4 | d'4. d'8 d'8 d'8 | e'2 d'8\( d'8\) | b4 cs'4. d'8 | d'2
}
tenor = { \globalParts
  \time 3/4 \partial 4 fs4 | fs4. g8 fs4 | a4 a4 a4 | b4. b8 a4 | a4 fs4 a4 | a4. a8 a4 | a4 gs4 a4 | a4. d'8 d'4 | cs'2 cs'4 | cs'4. b8 a4 | a4 a4 a4 | b2 a8 a8 | a4 fs4 fs4 | g4. fs8 g8 g8 | e4( a4) a8\( a8\) | g4 g4. fs8 | fs2
}
bass = { \globalParts
  \time 3/4 \partial 4 d4 | d4. d8 d4 | d4 e4 fs4 | e4. e8 a4 | d4 d4 d4 | cs4. cs8 cs4 | b,4 e4 a,4 | d4. b,8 e4 | a,2 a4 | g4. g8 g4 | fs4 fs4 fs4 | e2 a8 a8 | d4 d4 d4 | b,4. a,8 g,8 b,8 | cs2 d8\( d8\) | e4 a,4. d8 | d2
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l We gath -- er to -- geth -- er to ask the Lord's bless -- ing.
\l He chas -- tens and has -- tens his will to make known.
\l The wick -- ed op -- press -- ing now cease from dis -- tress -- ing.
\l Sing prais -- es to his name, he for -- gets not his own.
}
verseB = \lyricmode {
Be -- side us to guide us, our God with us join -- ing,
or -- dain -- ing, main -- tain -- ing his king -- dom di -- vine.
So from the be -- gin -- ning the fight we were win -- ning;
thou, Lord, wast at our side, all _ glo -- ry be thine!
}
verseC = \lyricmode {
We all do ex -- tol thee, thou Lead -- er tri -- um -- phant,
and pray that thou still our de -- fend -- er wilt be.
Let thy con -- gre -- ga -- tion es -- cape trib -- u -- la -- tion.
Thy name be ev -- er praised! O _ Lord, make us free!
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/3verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-3verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
