\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: William B. Bradbury," \italic "Cottage Melodies," "1859" }
poet = \smallText \markup { "Text: anonymous," \italic "The New York Observer," "1845" }
meter = \smallText "SWEET HOUR LMD"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 3
tags = "english christian 4part"
dateAdded = "2026-08-02"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Sweet hour of prayer"
hymnKey = \key d \major
hymnTime = \time 6/8
hymnBaseMoment = \set Timing.baseMoment = #(ly:make-moment 1/8)
hymnBeatStructure = \set Timing.beatStructure = 3,3
quarternoteTempo = 68
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  \partial 8 d'8 | fs'4 g'8 a'4 a'8 | b'4 cs''8 d''4 b'8 | a'4 fs'8 \pa fs'8( e'8) d'8 \pt | e'4 fs'8 e'4 \bar "" \break
  \partial 8 d'8 | fs'4 g'8 a'4 a'8 | b'4 cs''8 d''4 b'8 | a'4 fs'8 fs'4 d'8 | fs'4 e'8 d'4 \bar "" \break 
  \partial 8 a'8 | d''4 cs''8 d''4 b'8 | a'4 fs'8 a'4 a'8 | d''4 cs''8 d''4 b'8 | a'4 fs'8 e'4 \bar "" \break
  \partial 8 d'8 | fs'4 g'8 a'4 a'8 | b'4 cs''8 d''4 b'8 | a'4 fs'8 fs'4 d'8 | fs'4 e'8 d'4
\bar "|."
}
alto = { \globalParts
  \partial 8 d'8 | d'4 e'8 fs'4 fs'8 | g'4 a'8 b'4 g'8 | fs'4 d'8 d'8( cs'8) d'8 | cs'4 d'8 cs'4 d'8 | d'4 e'8 fs'4 fs'8 | g'4 a'8 b'4 g'8 | fs'4 d'8 d'4 d'8 | d'4 cs'8 d'4 fs'8 | fs'4 g'8 a'4 g'8 | fs'4 d'8 fs'4 fs'8 | fs'4 g'8 a'4 g'8 | fs'4 d'8 cs'4 d'8 | d'4 e'8 fs'4 fs'8 | g'4 a'8 b'4 g'8 | fs'4 d'8 d'4 d'8 | d'4 cs'8 d'4
}
tenor = { \globalParts
  \partial 8 fs8 | a4 a8 a4 d'8 | d'4 d'8 d'4 d'8 | d'4 a8 \pa a8( g8) fs8 \pt | a4 a8 a4 fs8 | a4 a8 a4 d'8 | d'4 d'8 d'4 d'8 | d'4 a8 a4 a8 | a4 g8 fs4 a8 | a4 a8 a4 d'8 | d'4 a8 a4 a8 | a4 a8 a4 d'8 | d'4 a8 a4 fs8 | a4 a8 a4 d'8 | d'4 d'8 d'4 d'8 | d'4 a8 a4 a8 | a4 g8 fs4
}
bass = { \globalParts
  \partial 8 d8 | d4 d8 d4 d8 | g4 g8 g4 g8 | d4 d8 d4 d8 | a,4 a,8 a,4 d8 | d4 d8 d4 d8 | g4 g8 g4 g8 | d4 d8 d4 fs8 | a4 a,8 d4 d8 | d4 e8 fs4 g8 | d4 d8 d4 d8 | d4 e8 fs4 g8 | d4 d8 a,4 d8 | d4 d8 d4 d8 | g4 g8 g4 g8 | d4 d8 d4 fs8 | a4 a,8 d4
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l Sweet hour of prayer, sweet hour of prayer, that calls me from a world of care,
\l and bids me at my Fa -- ther's throne make all my wants and wish -- es known;
\l in sea -- sons of dis -- tress and grief, my soul has of -- ten found re -- lief,
\l and oft es -- caped the tempt -- er's snare, by thy re -- turn, sweet hour of prayer!
}
verseB = \lyricmode {
Sweet hour of prayer, sweet hour of prayer, the joys I feel, the bliss I share,
of those whose anx -- ious spir -- its burn with strong de -- sires for thy re -- turn!
With such I has -- ten to the place where God my Sav -- ior shows his face,
and glad -- ly take my sta -- tion there, and wait for thee, sweet hour of prayer!
}
verseC = \lyricmode {
Sweet hour of prayer, sweet hour of prayer, thy wings shall my pe -- ti -- tion bear
to him whose truth and faith -- ful -- ness en -- gage the wait -- ing soul to bless.
And since he bids me seek his face, be -- lieve his word and trust his grace,
I'll cast on him my ev -- 'ry care, and wait for thee, sweet hour of prayer!
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/3verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-3verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
