\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText \markup { "Music: Burgoyne's" \italic "Collection," "1827" }
%% Wrapped: on one line this ran past the right margin and clipped the
%% composer text next to it ("Collection, 18").
poet = \twoLineSmallText \markup { "Text: Charles Wesley," } \markup { \italic "Short Hymns on Select Passages of Holy Scripture," "1762" }
meter = \smallText "SPANISH CHANT 77. 77. 77"

arranger = \smallText "arr. Benjamin Carr"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 1
tags = "english christian 4part"
dateAdded = "2026-07-26"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "Come, divine Interpreter"
hymnKey = \key bf \major
hymnTime = \time 2/2
quarternoteTempo = 110
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  bf'4. bf'8 a'4 bf'4 | g'4 bf'4 f'2 | d''4 bf'4 ef''4 c''4 | bf'4 a'4 bf'2 | d''4. d''8 c''4 d''4 | ef''4 d''4 c''2 | d''4. d''8 c''4 d''4 | ef''4 d''4 c''2 | bf'4. bf'8 a'4 bf'4 | g'4 bf'4 f'2 | d''4 bf'4 ef''4 c''4 | bf'4 a'4 bf'2
\bar "|."
}
alto = { \globalParts
  f'4. f'8 f'4 f'4 | ef'4 ef'4 d'2 | f'4 f'4 g'4 g'4 | f'4 ef'4 d'2 | f'4. f'8 f'4 f'4 | f'4 f'4 f'2 | f'4. f'8 f'4 f'4 | f'4 f'4 f'2 | f'4. f'8 f'4 f'4 | ef'4 ef'4 d'2 | f'4 f'4 g'4 g'4 | f'4 ef'4 d'2
}
tenor = { \globalParts
  d'4. d'8 c'4 bf4 | bf4 bf4 bf2 | bf4 bf4 bf4 ef'4 | d'4 c'4 bf2 | bf4. bf8 a4 bf4 | c'4 bf4 a2 | bf4. bf8 a4 bf4 | c'4 bf4 a2 | d'4. d'8 c'4 bf4 | bf4 bf4 bf2 | bf4 bf4 bf4 ef'4 | d'4 c'4 bf2
}
bass = { \globalParts
  bf,4. bf,8 c4 d4 | ef4 g4 bf2 | bf,4 d4 ef4 ef4 | f4 f4 bf,2 | bf4. bf8 f4 bf4 | a4 bf4 f2 | bf4. bf8 f4 bf4 | a4 bf4 f2 | bf,4. bf,8 c4 d4 | ef4 g4 bf2 | bf,4 d4 ef4 ef4 | f4 f4 bf,2
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l Come, di -- vine In -- ter -- pre -- ter, bring us eyes thy book to read, ears the mys -- tic words to hear, words which did from thee pro -- ceed, words that end -- less bliss im -- part, kept in an o -- be -- dient heart. 
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/1verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-1verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
