\version "2.22.1"
#(ly:set-option 'relative-includes #t)
\include "../../lib/hymn-common.ily"

%% MANUAL INFO
composer = \smallText "Music: Conrad G. Lint"
poet = \smallText \markup { "Text: John Newton," \italic "Olney Hymns, Book III," "1779" }
meter = \smallText "FELLOWSHIP 87.87"

%arranger = \smallText "arr. Name, year"
%% Note: the meter variable requires a TUNE NAME, following by a meter, for page generation to work. See existing songs for examples
%subtitle = \smallText "Optional"
%prescore_text = \prescoreText "Uncomment to add text up and left of the score"
%postscore_text = \postscoreText "Uncomment to add text down and left of the score"

verseCount = 2
tags = "english christian 4part"
dateAdded = "2026-08-02"
typesetter = "Kenan Schaefkofer"

% This file fragment was generated by from-xml.py
title = \titleText "May the grace of Christ our Savior"
hymnKey = \key d \major
hymnTime = \time 6/4
quarternoteTempo = 150
\include "../../lib/global-parts.ily"
\include "../../lib/header.ily"

soprano = { \globalParts
  fs'2 fs'4 a'2 fs'4 | e'4( fs'4) g'4 g'4 fs'2 | a'2 a'4 fs'2 g'4 | fs'2 e'4 fs'2. | b'2 b'4 g'2 b'4 | d''2 b'4 b'4 a'2 | a'2 b'4 a'2 g'4 | fs'2 e'4 fs'2. \bar "||" | g'2. fs'2. | e'2. d'2.
\bar "|."
}
alto = { \globalParts
  d'2 d'4 fs'2 d'4 | cs'4( d'4) e'4 e'4 d'2 | d'2 d'4 d'2 d'4 | d'2 cs'4 d'2. | d'2 d'4 d'2 d'4 | g'2 g'4 g'4 fs'2 | fs'2 g'4 fs'2 e'4 | d'2 cs'4 d'2. | d'2. d'2. | cs'2. a2.
}
tenor = { \globalParts
  a2 a4 d'2 a4 | a2 a4 a4 a2 | fs2 fs4 a2 b4 | a2 a4 a2. | g2 g4 b2 g4 | b2 d'4 d'4 d'2 | d'2 d'4 d'2 b4 | a2 a4 a2. | b2. a2. | a4( g2) fs2.
}
bass = { \globalParts
  d2 d4 d2 d4 | a,2 a,4 d4 d2 | d2 d4 d2 g,4 | a,2 a,4 d2. | g2 g4 g2 g4 | g2 g4 d4 d2 | d2 d4 d2 g4 | a2 a,4 d2. | g,2. d2. | a,2. d2.
}

%CHORDS
songChords = \chords {
  \globalChordSymbols
}

verseA = \lyricmode {
\l May the grace of Christ our Sav -- ior, and the Fa -- ther's bound -- less love, with the Ho -- ly Spir -- it's fa -- vor, rest up -- on us from a -- bove. A -- men A -- men 
}
verseB = \lyricmode {
Thus may we a -- bide in un -- ion with each oth -- er and the Lord, and pos -- sess, in sweet com -- mun -- ion, joys which earth can -- not af -- ford. 
}



% Set up music-aligned verses. Change to the correct number
\include "../../lib/2verse.ily"

%% Use this, or the tradStaffZoom and shapeStaffZoom equivalents, if space is tight.
%clairStaffZoom = #.9

%% All sheet music outputs
\include "../../lib/all-notation-outputs.ily"
% Slides output. Change to the correct number
\include "../../lib/slides-book-2verse.ily"
%% MIDI output
\include "../../lib/midi-output.ily"
